import type { BlogArticleData } from "./article-types";

export const drugNegotiationArticle: BlogArticleData = {
  slug: "medicare-drug-price-negotiation-program-explained",
  seo: {
    title: "Medicare Drug Price Negotiation Program: What It Means for You",
    description: "Medicare can now negotiate drug prices. Learn which drugs cost less in 2026 and 2027, how much you could save, and what is coming next.",
    canonical: "https://www.medicarefaq.com/blog/medicare-drug-price-negotiation-program-explained/",
    ogImage: "https://d2xsxph8kpxj0f.cloudfront.net/310519663444965628/gUNDzJhadva78ZtnmXvVsR/drug-negotiation-hero-Pw3fEbLVqPc8Qq3WzW3hwg.png",
    focusKeyword: "medicare drug price negotiation",
  },
  title: "Medicare's Drug Price Negotiation Program: What It Means for Beneficiaries in 2026 and Beyond",
  excerpt: "For the first time in history, Medicare can negotiate prescription drug prices directly with pharmaceutical companies. Ten drugs already have lower prices in 2026, with 15 more coming in 2027. Here is what this means for your out-of-pocket costs.",
  category: "Medicare News",
  categoryColor: "#2563EB",
  date: "July 17, 2026",
  author: "David Haass",
  reviewer: "Ashlee Zareczny",
  readTime: "12 min read",
  featured: true,
  image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663444965628/gUNDzJhadva78ZtnmXvVsR/drug-negotiation-hero-Pw3fEbLVqPc8Qq3WzW3hwg.png",
  imageAlt: "Prescription medication bottles arranged on a pharmacy counter representing lower drug costs through Medicare negotiation",
  keyTakeaways: [
    "Medicare negotiated prices for 10 high-cost Part D drugs took effect January 1, 2026, saving beneficiaries an estimated $1.5 billion in the first year alone.",
    "Fifteen additional drugs will have negotiated prices starting January 1, 2027, including Ozempic/Wegovy (71% discount), cancer drugs like Ibrance (50% off), and Trelegy Ellipta (73% off).",
    "The $2,100 annual Part D out-of-pocket cap works alongside negotiated prices, meaning many beneficiaries on expensive medications will hit their cap faster and pay nothing for the rest of the year.",
    "Part B drugs (administered in clinics, including cancer infusions) will enter negotiation for the first time in 2028, with prices effective in 2029.",
    "CMS proposed a permanent framework in June 2026 that will expand the program to up to 20 new drugs per year going forward."
  ],
  tableOfContents: [
    { id: "what-is-the-medicare-drug-price-negotiation-program", title: "What Is the Medicare Drug Price Negotiation Program?" },
    { id: "the-10-drugs-with-lower-prices-in-2026", title: "The 10 Drugs with Lower Prices in 2026" },
    { id: "15-more-drugs-coming-in-2027", title: "15 More Drugs Coming in 2027" },
    { id: "whats-coming-in-2028-and-beyond", title: "What Is Coming in 2028 and Beyond" },
    { id: "how-negotiated-prices-work-with-the-oop-cap", title: "How Negotiated Prices Work with the Out-of-Pocket Cap" },
    { id: "what-this-means-for-cancer-patients", title: "What This Means for Cancer Patients" },
    { id: "could-lower-drug-prices-affect-your-access-to-care", title: "Could Lower Drug Prices Affect Your Access to Care?" },
    { id: "what-you-should-do-now", title: "What You Should Do Now" },
  ],
  sections: [
    { type: "paragraph", content: "For decades, Medicare was prohibited by law from negotiating prescription drug prices with pharmaceutical companies. While the Department of Veterans Affairs, Medicaid, and even private insurers could bargain for lower prices, Medicare had to accept whatever price drug manufacturers set. That changed with the Inflation Reduction Act of 2022, which gave Medicare the authority to directly negotiate prices for certain high-cost drugs for the first time in the program's history." },
    { type: "paragraph", content: "The results are now real. As of January 1, 2026, ten of the most expensive drugs covered under [Medicare Part D](/original-medicare/medicare-parts/medicare-part-d) have negotiated prices in effect. Fifteen more drugs will see price reductions starting January 2027. And in June 2026, CMS proposed a permanent framework that will expand the program to include Part B drugs (those administered in doctors' offices and clinics) beginning in 2029. This article explains what the program means for you as a Medicare beneficiary, which drugs are affected, and how much you could save." },

    { type: "heading", level: 2, text: "What Is the Medicare Drug Price Negotiation Program?", id: "what-is-the-medicare-drug-price-negotiation-program" },
    { type: "paragraph", content: "The Medicare Drug Price Negotiation Program (MDPNP) allows CMS to negotiate directly with pharmaceutical companies to set a Maximum Fair Price (MFP) for certain high-cost drugs. The program targets drugs that meet specific criteria: they must be single-source (no generic or biosimilar competition), have been on the market for at least 7 years (or 11 years for biologics), and rank among the highest-spending drugs in Medicare." },
    { type: "paragraph", content: "The negotiation process is structured and transparent. CMS considers factors including the drug's clinical effectiveness, the availability of therapeutic alternatives, research and development costs, and the drug's current net price after rebates. Drug companies participate voluntarily, though opting out carries significant financial penalties. Once a price is agreed upon, it becomes the maximum amount that Medicare Part D plans pay for that drug, and beneficiary cost-sharing is calculated based on the lower negotiated price rather than the original list price." },
    { type: "callout", calloutType: "info", calloutTitle: "How the Program Expands Over Time", calloutText: "Year 1 (2026): 10 Part D drugs. Year 2 (2027): 15 Part D drugs. Year 3 (2028): 15 Part B and Part D drugs. Year 4 onward (2029+): Up to 20 new drugs per year, including Part B drugs administered in clinics." },

    { type: "heading", level: 2, text: "The 10 Drugs with Lower Prices in 2026", id: "the-10-drugs-with-lower-prices-in-2026" },
    { type: "paragraph", content: "The first round of negotiated prices took effect on January 1, 2026. These 10 drugs accounted for $56.2 billion in total Part D spending in 2023 and were used by approximately 8.8 million Medicare beneficiaries. CMS estimates that if these negotiated prices had been in effect during 2023, Medicare would have saved $6 billion (a 22% reduction in net spending), and beneficiaries would have saved $1.5 billion in out-of-pocket costs." },
    { type: "table", title: "2026 Negotiated Drug Prices (First 10 Drugs)", headers: ["Drug Name", "Treats", "Negotiated Price (30-day)", "Previous List Price", "Savings"], rows: [
      ["Eliquis", "Blood clots, stroke prevention", "$231", "$521", "56%"],
      ["Jardiance", "Type 2 diabetes, heart failure", "$197", "$573", "66%"],
      ["Xarelto", "Blood clots, stroke prevention", "$197", "$517", "62%"],
      ["Januvia", "Type 2 diabetes", "$113", "$527", "79%"],
      ["Farxiga", "Diabetes, heart failure, CKD", "$178", "$556", "68%"],
      ["Entresto", "Heart failure", "$295", "$628", "53%"],
      ["Enbrel", "Rheumatoid arthritis, psoriasis", "$2,355", "$7,106", "67%"],
      ["Imbruvica", "Blood cancers (CLL, MCL)", "$9,319", "$14,934", "38%"],
      ["Stelara", "Psoriasis, Crohn's disease", "$4,695", "$13,836", "66%"],
      ["Fiasp/NovoLog", "Diabetes (insulin)", "$119", "$495", "76%"]
    ], footnote: "Source: CMS Fact Sheet, August 2024. Prices represent 30-day supply at the Maximum Fair Price." },
    { type: "paragraph", content: "If you currently take any of these medications, you should already be seeing lower costs at the pharmacy. The negotiated price replaces the previous list price for purposes of calculating your copay or coinsurance under your Part D plan. For example, a beneficiary taking Januvia who previously paid a percentage of the $527 list price now pays a percentage of the $113 negotiated price instead." },

    { type: "heading", level: 2, text: "15 More Drugs Coming in 2027", id: "15-more-drugs-coming-in-2027" },
    { type: "paragraph", content: "CMS completed its second round of negotiations in November 2025, and 15 additional Part D drugs will have negotiated prices effective January 1, 2027. These drugs accounted for $42.5 billion in total Part D spending in 2024 and were used by 5.3 million beneficiaries. CMS estimates even greater savings from this round: $12 billion in net Medicare savings (44% lower spending) and $685 million in direct beneficiary out-of-pocket savings." },
    { type: "table", title: "2027 Negotiated Drug Prices (15 Drugs)", headers: ["Drug Name", "Treats", "Negotiated Price (30-day)", "Previous List Price", "Savings"], rows: [
      ["Ozempic/Rybelsus/Wegovy", "Diabetes, obesity, cardiovascular disease", "$274", "$959", "71%"],
      ["Trelegy Ellipta", "Asthma, COPD", "$175", "$654", "73%"],
      ["Xtandi", "Prostate cancer", "$7,004", "$13,480", "48%"],
      ["Pomalyst", "Multiple myeloma", "$8,650", "$21,744", "60%"],
      ["Ofev", "Pulmonary fibrosis", "$6,350", "$12,622", "50%"],
      ["Ibrance", "Breast cancer", "$7,871", "$15,741", "50%"],
      ["Linzess", "IBS, chronic constipation", "$136", "$539", "75%"],
      ["Calquence", "CLL, mantle cell lymphoma", "$8,600", "$14,228", "40%"],
      ["Austedo/XR", "Tardive dyskinesia, Huntington's", "$4,093", "$6,623", "38%"],
      ["Breo Ellipta", "Asthma, COPD", "$67", "$397", "83%"],
      ["Xifaxan", "Hepatic encephalopathy, IBS", "$1,000", "$2,696", "63%"],
      ["Vraylar", "Bipolar disorder, depression", "$770", "$1,376", "44%"],
      ["Tradjenta", "Type 2 diabetes", "$78", "$488", "84%"],
      ["Janumet/XR", "Type 2 diabetes", "$80", "$526", "85%"],
      ["Otezla/XR", "Psoriasis, psoriatic arthritis", "$1,650", "$4,722", "65%"]
    ], footnote: "Source: CMS Fact Sheet, November 2025. Prices represent 30-day supply at the Maximum Fair Price." },
    { type: "paragraph", content: "The 2027 list includes several blockbuster medications that affect millions of beneficiaries. Ozempic and Wegovy (semaglutide), which treat diabetes, cardiovascular disease, and obesity, will drop from $959 to $274 per month, a 71% reduction. This is particularly significant because Ozempic alone accounted for over $15 billion in Medicare Part D spending in 2024. Breo Ellipta, used by over 626,000 beneficiaries for asthma and COPD, will see an 83% price cut, dropping from $397 to just $67 per month." },
    { type: "callout", calloutType: "tip", calloutTitle: "Check Your Formulary During AEP", calloutText: "If you take any of the 2027 negotiated drugs, review your Part D plan during the Annual Enrollment Period (October 15 through December 7, 2026). Some plans may adjust their formulary tiers or cost-sharing structures in response to the new prices. Use the Medicare Plan Finder at Medicare.gov to compare your options." },

    { type: "heading", level: 2, text: "What Is Coming in 2028 and Beyond", id: "whats-coming-in-2028-and-beyond" },
    { type: "paragraph", content: "In January 2026, CMS announced 15 drugs selected for the third round of negotiations. For the first time, this list includes drugs covered under Medicare Part B, which are medications administered in doctors' offices, outpatient clinics, and infusion centers. Negotiated prices for these drugs will take effect January 1, 2028." },
    { type: "table", title: "Drugs Selected for 2028 Negotiation", headers: ["Drug Name", "Treats", "Total Medicare Spending", "Beneficiaries"], rows: [
      ["Trulicity", "Type 2 diabetes, cardiovascular disease", "$4.9 billion", "617,000"],
      ["Biktarvy", "HIV", "$3.9 billion", "101,000"],
      ["Orencia", "Rheumatoid arthritis, psoriatic arthritis", "$2.5 billion", "72,000"],
      ["Cosentyx", "Psoriasis, psoriatic arthritis", "$2.3 billion", "40,000"],
      ["Erleada", "Prostate cancer", "$1.9 billion", "19,000"],
      ["Kisqali", "Breast cancer", "$1.6 billion", "17,000"],
      ["Entyvio", "Crohn's disease, ulcerative colitis", "$1.5 billion", "37,000"],
      ["Verzenio", "Breast cancer", "$1.4 billion", "15,000"],
      ["Botox", "Chronic migraine, spasticity", "$1.1 billion", "390,000"],
      ["Lenvima", "Thyroid, liver, kidney cancer", "$1.1 billion", "10,000"],
      ["Xolair", "Asthma, chronic urticaria", "$1.1 billion", "40,000"],
      ["Rexulti", "Depression, schizophrenia", "$1.1 billion", "119,000"],
      ["Xeljanz/XR", "Rheumatoid arthritis, UC", "$1.0 billion", "22,000"],
      ["Anoro Ellipta", "COPD", "$813 million", "281,000"],
      ["Cimzia", "Crohn's, psoriasis, RA", "$787 million", "38,000"]
    ], footnote: "Source: CMS Selected Drug List, January 2026. Spending data from November 2024 through October 2025." },
    { type: "paragraph", content: "Looking further ahead, CMS published a 133-page proposed rule in June 2026 establishing a permanent framework for the program. Starting with the fourth cycle (prices effective in 2029), up to 20 new drugs will be selected each year. This is also when Part B drugs, including expensive infused cancer treatments like Keytruda (pembrolizumab), are expected to enter negotiation. Keytruda is the single highest-spending drug in all of Medicare Part B, accounting for $5.6 billion in 2023 spending alone." },

    { type: "heading", level: 2, text: "How Negotiated Prices Work with the Out-of-Pocket Cap", id: "how-negotiated-prices-work-with-the-oop-cap" },
    { type: "paragraph", content: "The drug price negotiation program works in tandem with another major Inflation Reduction Act provision: the annual [Part D out-of-pocket cap](/blog/how-is-medicare-part-d-changing-in-2026). In 2026, no Medicare beneficiary will pay more than $2,100 out of pocket for covered Part D prescription drugs in a calendar year. Once you hit that cap, your Part D plan covers 100% of your remaining drug costs for the rest of the year." },
    { type: "paragraph", content: "Here is how the two provisions interact: because negotiated prices lower the total cost of your drugs, your copays and coinsurance at the pharmacy are calculated on a smaller amount. This means your out-of-pocket spending accumulates more slowly toward the $2,100 cap. For beneficiaries taking multiple expensive medications, you may find that you no longer hit the cap at all, saving money throughout the entire year rather than just after reaching catastrophic coverage." },
    { type: "paragraph", content: "For beneficiaries on a single high-cost drug, the math works differently. If you take Imbruvica for chronic lymphocytic leukemia, for example, even at the negotiated price of $9,319 per month, your cost-sharing will still push you to the $2,100 cap relatively quickly. But you will reach it paying less each month along the way, and the Medicare Prescription Payment Plan (M3P) allows you to spread that $2,100 into predictable monthly installments of $175 per month." },
    { type: "callout", calloutType: "info", calloutTitle: "The Medicare Prescription Payment Plan (M3P)", calloutText: "Starting in 2025, the M3P lets you spread your annual Part D out-of-pocket costs into equal monthly payments rather than paying large amounts upfront. If your total annual drug costs will reach the $2,100 cap, you can pay approximately $175 per month instead of facing a large bill in January. Contact your Part D plan to enroll." },

    { type: "heading", level: 2, text: "What This Means for Cancer Patients", id: "what-this-means-for-cancer-patients" },
    { type: "paragraph", content: "Cancer patients stand to benefit significantly from the negotiation program. Several of the most expensive cancer drugs are included in the first three rounds of negotiations, covering blood cancers, breast cancer, prostate cancer, and multiple myeloma. The savings for these medications are substantial." },
    { type: "table", title: "Cancer Drugs in the Negotiation Program", headers: ["Drug", "Cancer Type", "Year Effective", "Price Reduction"], rows: [
      ["Imbruvica", "CLL, mantle cell lymphoma", "2026", "38% (from $14,934 to $9,319/month)"],
      ["Xtandi", "Prostate cancer", "2027", "48% (from $13,480 to $7,004/month)"],
      ["Pomalyst", "Multiple myeloma", "2027", "60% (from $21,744 to $8,650/month)"],
      ["Ibrance", "Breast cancer", "2027", "50% (from $15,741 to $7,871/month)"],
      ["Calquence", "CLL, mantle cell lymphoma", "2027", "40% (from $14,228 to $8,600/month)"],
      ["Erleada", "Prostate cancer", "2028", "TBD"],
      ["Kisqali", "Breast cancer", "2028", "TBD"],
      ["Verzenio", "Breast cancer", "2028", "TBD"],
      ["Lenvima", "Thyroid, liver, kidney cancer", "2028", "TBD"]
    ] },
    { type: "paragraph", content: "For oral cancer drugs covered under Part D, the $2,100 annual out-of-pocket cap provides an absolute ceiling on what you will pay. A beneficiary taking Pomalyst for multiple myeloma previously faced potential annual costs exceeding $6,000 out of pocket before reaching catastrophic coverage. Now, with the negotiated price and the OOP cap combined, the maximum annual cost is $2,100 regardless of how expensive the drug is." },
    { type: "paragraph", content: "However, many cancer drugs are administered intravenously in clinics and covered under [Medicare Part B rather than Part D](/blog/why-some-drugs-are-covered-under-part-b-instead-of-part-d). These include immunotherapy drugs like Keytruda, infused chemotherapy regimens, and targeted biologics. Part B drugs are not yet subject to negotiated prices (that begins in 2029), and Part B has no annual out-of-pocket cap under Original Medicare. Beneficiaries receiving Part B cancer drugs pay 20% coinsurance with no limit, which is why having a [Medicare Supplement plan](/medicare-supplement-plans) or a [Medicare Advantage plan](/medicare-part-c/medicare-advantage-plans) with a maximum out-of-pocket limit is critical for cancer patients." },

    { type: "heading", level: 2, text: "Could Lower Drug Prices Affect Your Access to Care?", id: "could-lower-drug-prices-affect-your-access-to-care" },
    { type: "paragraph", content: "While lower drug prices are unambiguously good for beneficiaries at the pharmacy counter, some healthcare policy experts have raised concerns about potential downstream effects, particularly for drugs covered under Part B. Medical oncology practices, for example, derive 70 to 80 percent of their revenue from medications they purchase and administer to patients. Medicare reimburses these practices at the drug's Average Sales Price plus a 6% add-on fee. When the price of a drug drops significantly, that 6% margin shrinks proportionally." },
    { type: "paragraph", content: "Industry observers have noted that if Part B drug prices are cut by 40 to 60 percent through negotiation (as has happened with Part D drugs), independent oncology practices could face serious financial pressure. Some may consolidate, be acquired by hospital systems or private equity firms, or close satellite offices in rural areas. This is a concern worth monitoring, though it is important to note that Part B negotiation does not begin until 2029, and CMS has indicated it will consider the impact on provider access when setting prices." },
    { type: "paragraph", content: "For beneficiaries, the practical takeaway is this: if you receive infused medications at an independent clinic, pay attention to whether your provider remains in your network and continues offering services in your area. If your oncologist or specialist practice changes ownership or location, your Medicare Advantage plan's network may be affected. Beneficiaries on Original Medicare with a Medigap plan have more flexibility, since they can see any Medicare-accepting provider nationwide." },
    { type: "callout", calloutType: "warning", calloutTitle: "Proposed Legislation to Watch", calloutText: "The Protecting Patient Access to Cancer and Complex Therapies Act (H.R. 4299) has been introduced in Congress to address provider reimbursement concerns. If passed, it could modify how Medicare pays for negotiated Part B drugs to preserve access at independent practices. The public comment period for CMS's permanent negotiation framework closes August 17, 2026." },

    { type: "heading", level: 2, text: "What You Should Do Now", id: "what-you-should-do-now" },
    { type: "paragraph", content: "If you take any of the 10 drugs with negotiated prices already in effect, verify that your pharmacy is charging you based on the new lower price. Your Part D plan should automatically apply the Maximum Fair Price, but it is worth checking your Explanation of Benefits statements to confirm your cost-sharing reflects the reduced amount." },
    { type: "paragraph", content: "If you take any of the 15 drugs with negotiated prices starting in 2027, mark the [Annual Enrollment Period](/medicare-enrollment/annual-changes) (October 15 through December 7, 2026) on your calendar. This is your opportunity to review Part D plans and ensure you are in a plan that offers the best formulary placement and cost-sharing for your medications at the new prices. Some plans may restructure their tiers in response to negotiated prices." },
    { type: "paragraph", content: "For beneficiaries taking expensive medications who expect to reach the $2,100 out-of-pocket cap, consider enrolling in the Medicare Prescription Payment Plan (M3P) to spread your costs into predictable monthly payments. Contact your Part D plan directly to sign up." },
    { type: "paragraph", content: "Finally, if you are on Original Medicare without supplemental coverage and take Part B drugs (infused medications), strongly consider enrolling in a [Medigap plan](/medicare-supplement-plans/plan-g) to cover the 20% coinsurance, or evaluate [Medicare Advantage plans](/medicare-part-c/medicare-advantage-plans) with lower maximum out-of-pocket limits. Until Part B negotiation takes effect in 2029, the 20% coinsurance on expensive infused drugs remains one of the largest financial risks for Medicare beneficiaries." },
  ],
  faqs: [
    { question: "Do I need to do anything to get the lower negotiated drug prices?", answer: "No. The negotiated prices are automatically applied by your Part D plan. You do not need to enroll in a new plan or take any action. Your copay or coinsurance at the pharmacy should already reflect the lower Maximum Fair Price for the 10 drugs effective in 2026." },
    { question: "Will the negotiated prices affect my Part D plan premiums?", answer: "Potentially. CMS has estimated that the Inflation Reduction Act provisions, including drug price negotiation, are helping to keep Part D premiums stable. The base beneficiary premium for 2026 is $38.99 per month, and annual premium increases are capped at 6% through 2029." },
    { question: "Are Medicare Advantage drug plans (MAPD) included in the negotiation program?", answer: "Yes. The negotiated Maximum Fair Prices apply to all Medicare Part D coverage, whether you have a standalone Part D plan paired with Original Medicare and Medigap, or a Medicare Advantage plan that includes drug coverage (MAPD)." },
    { question: "What if my drug is not on the negotiation list?", answer: "The program currently covers 25 drugs (10 in 2026, 15 in 2027) with 15 more selected for 2028. CMS will add up to 20 new drugs each year going forward. If your medication is not yet included, it may be selected in a future cycle. In the meantime, the $2,100 annual Part D out-of-pocket cap still protects you from catastrophic costs." },
    { question: "Does the $2,100 out-of-pocket cap apply to Part B drugs too?", answer: "No. The $2,100 annual cap applies only to Part D prescription drugs (those you pick up at a pharmacy or receive by mail). Part B drugs administered in clinical settings have no out-of-pocket cap under Original Medicare. A Medigap plan or Medicare Advantage plan is needed to limit Part B cost exposure." },
    { question: "When will cancer drugs like Keytruda have negotiated prices?", answer: "Keytruda (pembrolizumab) is expected to be selected for negotiation in the fourth cycle (IPAY 2029 or 2030). Part B drugs, including infused cancer treatments, will first enter negotiation with prices effective in 2029 at the earliest." },
  ],
  relatedSlugs: [
    "how-is-medicare-part-d-changing-in-2026",
    "why-some-drugs-are-covered-under-part-b-instead-of-part-d",
    "does-medicare-cover-chemotherapy",
    "medicare-and-prescription-drugs-whats-covered-and-whats-not",
    "what-is-a-medicare-part-d-formulary",
    "step-therapy-and-prior-authorization-what-medicare-beneficiaries-need-to-know",
    "medicare-part-d-payment-plan-2026",
    "medicare-coverage-for-cancer",
    "how-can-seniors-save-on-prescription-drug-costs",
  ],
};
