import type { CoverageArticleData } from "./article-types";

export const chemotherapyArticle: CoverageArticleData = {
  slug: "does-medicare-cover-chemotherapy",
  seo: {
    title: "Does Medicare Cover Chemotherapy? What You Pay in 2026",
    description: "Medicare covers chemotherapy under Part B and Part D. Learn what you pay for infused and oral chemo, how to reduce costs, and which cancer drugs now have negotiated prices.",
    canonical: "https://www.medicarefaq.com/faqs/does-medicare-cover-chemotherapy/",
    ogImage: "/images/medicarefaq-cover.jpg",
    focusKeyword: "does medicare cover chemotherapy",
  },
  title: "Does Medicare Cover Chemotherapy and Cancer Drugs?",
  subtitle: "Medicare covers most chemotherapy and cancer treatments, but your out-of-pocket costs depend on whether the drug is infused in a clinic (Part B) or taken orally at home (Part D). Here is what each plan type pays, what you owe, and how new negotiated drug prices are lowering costs for cancer patients.",
  category: "Medicare Coverage",
  dateUpdated: "July 17, 2026",
  lastReviewed: "2026-07-17",
  author: {
    name: "David Haass",
    initials: "DH",
    role: "Author",
    bio: "David Haass is a Medicare content writer at MedicareFAQ with extensive experience explaining Medicare benefits, enrollment, and coverage options to beneficiaries.",
  },
  reviewer: {
    name: "Ashlee Zareczny",
    initials: "AZ",
    role: "Reviewer",
    bio: "Ashlee Zareczny is the Compliance and Editorial Manager at MedicareFAQ, ensuring all Medicare content is accurate, up-to-date, and compliant with CMS guidelines.",
  },
  readTime: "9 min read",
  quickAnswer: {
    text: "Yes, Medicare covers chemotherapy and cancer drugs. Part B covers drugs administered in a doctor's office or outpatient clinic (infused chemo, immunotherapy, targeted therapy). Part D covers oral cancer medications you take at home. You pay 20% coinsurance for Part B drugs with no annual cap under Original Medicare, while Part D drugs are subject to the $2,100 annual out-of-pocket cap in 2026.",
    badges: [
      { plan: "Part A", status: "partial" },
      { plan: "Part B", status: "covered" },
      { plan: "Part D", status: "covered" },
      { plan: "Medicare Advantage", status: "covered" },
      { plan: "Medigap", status: "covered" },
    ],
  },
  comparisonTable: [
    { planType: "Infused Chemotherapy (Part B)", coverage: "Covered under Part B at outpatient facilities", icon: "shield", notes: "20% coinsurance after $283 deductible; Medigap covers the 20%; MA plans apply copay up to MOOP" },
    { planType: "Oral Cancer Drugs (Part D)", coverage: "Covered under Part D drug benefit", icon: "shield", notes: "Specialty tier placement; $2,000 annual OOP cap in 2026; MA-PD plans include drug coverage" },
    { planType: "Immunotherapy (Part B)", coverage: "Covered when administered by provider", icon: "shield", notes: "Keytruda, Opdivo, etc. billed under Part B; 20% coinsurance applies; negotiated prices coming 2028" },
    { planType: "Radiation Therapy (Part B)", coverage: "Covered at outpatient facilities", icon: "shield", notes: "20% coinsurance after deductible; typically 15-30 sessions; Medigap covers coinsurance" },
    { planType: "Inpatient Chemotherapy (Part A)", coverage: "Covered during hospital stays", icon: "shield", notes: "$1,736 deductible per benefit period; $0 coinsurance days 1-60; includes all drugs during stay" },
    { planType: "Annual Out-of-Pocket Protection", coverage: "Varies by plan type", icon: "heart", notes: "Original Medicare: no cap; MA: $8,850 max in-network (2026); Part D: $2,000 cap; Medigap: near $0" },
  ],
  planBreakdowns: [
    {
      planName: "Part B: Infused Chemotherapy and Immunotherapy",
      icon: "Syringe",
      iconColor: "text-blue-600",
      coverageLabel: "Covered",
      coverageType: "covered",
      paragraphs: [
        "Medicare Part B covers chemotherapy drugs, immunotherapy, and targeted therapy that are administered by a healthcare provider in an outpatient setting. This includes infusions given in your oncologist's office, hospital outpatient departments, and freestanding infusion centers. Part B also covers the administration itself, including the nursing time, supplies, and facility fees associated with your treatment.",
        "Medicare reimburses providers for Part B drugs at the Average Sales Price (ASP) plus 6%. You pay 20% of the Medicare-approved amount after meeting your annual Part B deductible of $283 in 2026. There is no annual cap on Part B out-of-pocket costs under Original Medicare, which means a year of expensive infused cancer treatment could cost you thousands in coinsurance alone.",
      ],
      whatItCovers: [
        "Infused chemotherapy drugs administered in a clinic or hospital outpatient department",
        "Immunotherapy drugs like pembrolizumab (Keytruda) and nivolumab (Opdivo)",
        "Targeted therapy biologics administered by injection or infusion",
        "Anti-nausea drugs administered during chemotherapy sessions",
        "Administration fees, nursing time, and supplies for infusion",
        "Blood tests and lab work related to chemotherapy monitoring",
      ],
      whatItDoesntCover: [
        "Oral chemotherapy drugs taken at home (covered under Part D)",
        "Experimental or investigational cancer treatments not approved by FDA",
        "Drugs administered during an inpatient hospital stay (covered under Part A)",
        "Over-the-counter supportive medications (anti-nausea pills taken at home, etc.)",
      ],
      callout: {
        type: "warning",
        title: "The 20% Coinsurance Problem for Cancer Patients",
        text: "A single infusion of Keytruda costs approximately $11,000. At 20% coinsurance, that is $2,200 per treatment, every 3 to 6 weeks. Over a year of treatment, your Part B coinsurance alone could exceed $15,000. This is why supplemental coverage (Medigap or Medicare Advantage) is essential for cancer patients on Original Medicare.",
      },
      costNote: "$ Cost: 20% coinsurance after the $283 Part B deductible (2026). No annual cap under Original Medicare. Medigap Plan G covers the full 20%.",
    },
    {
      planName: "Part D: Oral Cancer Medications",
      icon: "Pill",
      iconColor: "text-purple-600",
      coverageLabel: "Covered",
      coverageType: "covered",
      paragraphs: [
        "Oral cancer drugs that you take at home are covered under Medicare Part D. These include oral chemotherapy agents, hormone therapies, and targeted oral medications for various cancers. Many newer cancer treatments are oral, including drugs for breast cancer (Ibrance, Kisqali, Verzenio), prostate cancer (Xtandi, Erleada), blood cancers (Imbruvica, Calquence), and multiple myeloma (Pomalyst).",
        "Under Part D, oral cancer drugs are typically placed on Tier 4 (preferred specialty) or Tier 5 (non-preferred specialty), which carry the highest cost-sharing. However, the Inflation Reduction Act's $2,100 annual out-of-pocket cap means that no matter how expensive your oral cancer drug is, you will never pay more than $2,100 total for all Part D drugs in a calendar year. The Medicare Prescription Payment Plan (M3P) lets you spread this cost into monthly installments of approximately $175.",
      ],
      whatItCovers: [
        "Oral chemotherapy drugs (capecitabine, temozolomide, etc.)",
        "Oral targeted therapy (Ibrance, Xtandi, Imbruvica, Calquence, etc.)",
        "Hormone therapy drugs (letrozole, anastrozole, tamoxifen)",
        "Oral anti-nausea medications prescribed for chemo side effects",
        "Oral immunomodulators (Pomalyst, Revlimid)",
      ],
      whatItDoesntCover: [
        "Drugs not on your plan's formulary (may require exception or plan change)",
        "Over-the-counter supportive care medications",
        "Drugs used for experimental or off-label purposes not approved by your plan",
      ],
      callout: {
        type: "tip",
        title: "Negotiated Prices Are Lowering Cancer Drug Costs",
        text: "Several oral cancer drugs now have Medicare-negotiated prices: Imbruvica dropped 38% in 2026, while Xtandi (48%), Pomalyst (60%), Ibrance (50%), and Calquence (40%) will have lower prices starting January 2027. Combined with the $2,100 cap, cancer patients on Part D are seeing significant relief.",
      },
      costNote: "$ Cost: Varies by plan tier, but capped at $2,100 total out-of-pocket per year for all Part D drugs (2026). M3P available to spread costs monthly.",
    },
    {
      planName: "Medicare Advantage: Cancer Drug Coverage",
      icon: "Shield",
      iconColor: "text-teal-600",
      coverageLabel: "Covered with Annual MOOP Limit",
      coverageType: "covered",
      paragraphs: [
        "Medicare Advantage plans cover all the same cancer treatments as Original Medicare (Part A and Part B), plus most plans include Part D drug coverage (MAPD). The key difference is the annual maximum out-of-pocket (MOOP) limit. In 2026, the in-network MOOP for Medicare Advantage plans cannot exceed $8,850, meaning your total costs for Part A and Part B services are capped regardless of how many infusions or treatments you receive.",
        "However, Medicare Advantage plans use provider networks. If your oncologist or cancer center is not in your plan's network, you may face higher costs or need to switch providers. Some plans require prior authorization for cancer treatments, which can delay the start of therapy. Before enrolling in or staying with a Medicare Advantage plan after a cancer diagnosis, verify that your oncologist, hospital, and preferred cancer center are all in-network.",
      ],
      whatItCovers: [
        "All Part B cancer treatments (infused chemo, immunotherapy, radiation)",
        "Part D oral cancer drugs (included in MAPD plans)",
        "Annual MOOP limit protects against unlimited Part B coinsurance",
        "Some plans offer additional cancer support benefits (transportation, care coordination)",
      ],
      whatItDoesntCover: [
        "Out-of-network cancer treatment (unless PPO plan, at higher cost)",
        "Treatments denied due to prior authorization requirements",
        "Experimental treatments not covered by the plan",
      ],
      callout: {
        type: "info",
        title: "Network Considerations for Cancer Patients",
        text: "If you are diagnosed with cancer while enrolled in Medicare Advantage, verify immediately that your oncologist and preferred treatment facility are in-network. If you need to see an out-of-network specialist or travel to a cancer center, you may want to consider switching to Original Medicare with a Medigap plan during the appropriate enrollment period.",
      },
      costNote: "$ Cost: Copays and coinsurance up to the plan's annual MOOP ($8,850 max in-network for 2026). Part D drugs subject to the $2,100 OOP cap.",
    },
    {
      planName: "Medigap: Covering the 20% Coinsurance",
      icon: "Heart",
      iconColor: "text-rose-600",
      coverageLabel: "Covers Part B Cost-Sharing",
      coverageType: "covered",
      paragraphs: [
        "Medicare Supplement (Medigap) plans are specifically designed to cover the gaps in Original Medicare, including the 20% Part B coinsurance that makes infused cancer treatment so expensive. With a Medigap Plan G, for example, your only out-of-pocket cost for Part B cancer treatment is the $283 annual deductible. After that, Plan G pays 100% of the Medicare-approved coinsurance for all Part B services, including chemotherapy infusions, immunotherapy, radiation, and related lab work.",
        "This is why many Medicare advisors recommend Medigap for beneficiaries with cancer or at high risk for cancer. The predictability of costs is unmatched: you pay your monthly Medigap premium plus the $283 deductible, and everything else is covered. There are no networks, no prior authorization requirements, and no risk of surprise bills from out-of-network providers. You can see any oncologist in the country who accepts Medicare.",
      ],
      whatItCovers: [
        "20% Part B coinsurance for all infused cancer drugs",
        "Part A hospital deductible ($1,676 in 2026) for inpatient cancer stays",
        "Coinsurance for radiation therapy, lab work, and imaging",
        "Skilled nursing facility coinsurance (days 21-100)",
        "Nationwide provider access with no network restrictions",
      ],
      whatItDoesntCover: [
        "Part D prescription drugs (separate Part D plan required for oral chemo)",
        "Services not covered by Medicare (experimental treatments, etc.)",
        "Long-term custodial care",
      ],
      callout: {
        type: "tip",
        title: "Why Medigap Is Critical for Cancer Patients",
        text: "A cancer patient receiving Keytruda infusions every 3 weeks at $11,000 per infusion would pay over $15,000 per year in Part B coinsurance under Original Medicare alone. With Medigap Plan G, that same patient pays only $283 for the entire year. The monthly premium (typically $150-$300) is far less than the potential coinsurance exposure.",
      },
      costNote: "$ Cost: Monthly Medigap premium + $283 Part B deductible (Plan G). All Part B coinsurance for cancer treatment is then covered at 100%.",
    },
  ],
  legislativeUpdate: {
    title: "Medicare Drug Price Negotiation and Cancer Drugs",
    items: [
      { title: "Imbruvica Negotiated Price (2026)", status: "Passed", description: "Imbruvica (ibrutinib) for CLL and mantle cell lymphoma dropped 38% from $14,934 to $9,319 per month under Medicare's first round of drug price negotiations." },
      { title: "Cancer Drugs in 2027 Negotiation", status: "Passed", description: "Xtandi (48% cut), Pomalyst (60% cut), Ibrance (50% cut), and Calquence (40% cut) will have negotiated prices effective January 1, 2027." },
      { title: "2028 Cancer Drug Selections", status: "Pending", description: "Erleada (prostate), Kisqali (breast), Verzenio (breast), and Lenvima (thyroid/liver/kidney) are selected for negotiation with prices effective 2028." },
      { title: "Part B Cancer Drug Negotiation (2029)", status: "Proposed", description: "CMS proposed a permanent framework in June 2026 that will bring Part B infused drugs (including Keytruda) into negotiation starting with prices effective in 2029." },
    ],
  },
  faqs: [
    {
      question: "Does Medicare cover all types of chemotherapy?",
      answer: "Medicare covers FDA-approved chemotherapy drugs that are medically necessary for your cancer diagnosis. This includes traditional chemotherapy, immunotherapy, targeted therapy, and hormone therapy. Experimental or investigational treatments in clinical trials may have limited coverage.",
    },
    {
      question: "How much does chemotherapy cost with Medicare?",
      answer: "Under Part B, you pay 20% coinsurance after the $283 deductible with no annual cap. A Medigap plan covers this coinsurance. Under Part D, oral chemo is capped at $2,100 per year total out-of-pocket. Medicare Advantage caps all Part A/B costs at the plan's MOOP (up to $8,850 in 2026).",
    },
    {
      question: "Is oral chemotherapy covered under Part B or Part D?",
      answer: "Oral cancer drugs taken at home are covered under Part D. The exception is oral drugs that have an equivalent IV form that would be covered under Part B. In that case, Part B may cover the oral version at the same cost-sharing as the IV form.",
    },
    {
      question: "Do I need prior authorization for chemotherapy under Medicare?",
      answer: "Under Original Medicare, prior authorization is generally not required for chemotherapy. However, Medicare Advantage plans may require prior authorization for certain cancer treatments. If your MA plan denies authorization, you have the right to appeal.",
    },
    {
      question: "Which cancer drugs have lower prices from Medicare negotiation?",
      answer: "In 2026, Imbruvica (CLL/MCL) dropped 38%. In 2027, Xtandi (prostate, 48% cut), Pomalyst (myeloma, 60%), Ibrance (breast, 50%), and Calquence (CLL, 40%) will have negotiated prices. Erleada, Kisqali, Verzenio, and Lenvima are selected for 2028.",
    },
    {
      question: "Should I choose Medigap or Medicare Advantage if I have cancer?",
      answer: "Medigap provides more predictable costs and unrestricted provider access, which is often preferred for cancer patients who need specialist care. Medicare Advantage has a MOOP cap but may restrict your choice of oncologists and require prior authorization. Consider your treatment needs and provider preferences carefully.",
    },
  ],
  quickReference: [
    { icon: "check", text: "Part B covers infused chemo, immunotherapy, and targeted therapy at 20% coinsurance" },
    { icon: "check", text: "Part D covers oral cancer drugs with a $2,100 annual out-of-pocket cap (2026)" },
    { icon: "check", text: "Medigap Plan G covers the full 20% Part B coinsurance for cancer treatment" },
    { icon: "check", text: "Medicare Advantage caps total Part A/B costs at the plan MOOP ($8,850 max in 2026)" },
    { icon: "alert", text: "Original Medicare has NO annual cap on Part B out-of-pocket costs" },
    { icon: "dollar", text: "Several cancer drugs now have Medicare-negotiated prices (38-60% lower)" },
    { icon: "info", text: "The M3P lets you spread Part D costs into $175/month payments" },
  ],
  relatedTopics: [
    { title: "Medicare Coverage for Cancer Treatment", description: "Comprehensive guide to what Medicare covers for cancer diagnosis, treatment, and follow-up care.", slug: "medicare-coverage-for-cancer" },
    { title: "Medigap vs Medicare Advantage for Cancer", description: "Compare how Medigap and Medicare Advantage handle cancer treatment costs and provider access.", slug: "how-medigap-covers-cancer-compared-to-ma" },
    { title: "Why Some Drugs Are Part B Instead of Part D", description: "Understand why infused cancer drugs are covered differently than oral medications.", slug: "why-some-drugs-are-covered-under-part-b-instead-of-part-d" },
    { title: "Medicare Drug Price Negotiation Explained", description: "How Medicare's new drug negotiation program is lowering costs for cancer drugs and other medications.", slug: "medicare-drug-price-negotiation-program-explained" },
    { title: "How Is Part D Changing in 2026?", description: "Key changes including the $2,100 out-of-pocket cap and negotiated drug prices.", slug: "how-is-medicare-part-d-changing-in-2026" },
  ],
  sidebarRelatedLinks: [
    "medicare-coverage-for-cancer",
    "how-medigap-covers-cancer-compared-to-ma",
    "why-some-drugs-are-covered-under-part-b-instead-of-part-d",
    "medicare-drug-price-negotiation-program-explained",
    "how-is-medicare-part-d-changing-in-2026",
  ],
  ctaBanner: {
    title: "Diagnosed with Cancer? Get Help Choosing the Right Medicare Coverage",
    text: "The difference between Medigap and Medicare Advantage can mean thousands of dollars in cancer treatment costs. Our licensed agents can compare plans, explain your options for covering chemotherapy and immunotherapy, and help you find coverage that protects you financially. Call today for a free, no-obligation consultation.",
  },
  relatedSlugs: [
    "medicare-coverage-for-cancer",
    "how-medigap-covers-cancer-compared-to-ma",
    "why-some-drugs-are-covered-under-part-b-instead-of-part-d",
    "medicare-drug-price-negotiation-program-explained",
    "how-is-medicare-part-d-changing-in-2026",
    "what-is-a-medicare-part-d-formulary",
    "step-therapy-and-prior-authorization-what-medicare-beneficiaries-need-to-know",
    "medicare-and-prescription-drugs-whats-covered-and-whats-not",
  ],
};
