/**
 * Medigap by-state data
 * Used by MedigapStateTemplate.tsx
 */

export interface StateData {
  slug: string;
  name: string;
  abbreviation: string;
  isStandardized: boolean; // MA, MN, WI have their own standardization
  standardizationNote?: string;
  medicareEnrollees: string;
  avgPlanGPremium: string;
  topCarriers: string[];
  popularPlans: string[];
  openEnrollmentNote: string;
  stateSpecificRules: string[];
  overview: string;
  keyFacts: { label: string; value: string }[];
  canonical: string;
  metaTitle: string;
  metaDescription: string;
}

export const STATE_DATA: StateData[] = [
  {
    slug: "massachusetts-medigap-plans",
    name: "Massachusetts",
    abbreviation: "MA",
    isStandardized: false,
    standardizationNote: "Massachusetts has its own standardized Medigap plan structure that differs from the federal standard. Instead of lettered plans, Massachusetts offers Core, Supplement 1, and Supplement 1A plans.",
    medicareEnrollees: "1.3 million",
    avgPlanGPremium: "N/A (state-specific plans)",
    topCarriers: ["Blue Cross Blue Shield of MA", "Tufts Health Plan", "Harvard Pilgrim"],
    popularPlans: ["Supplement 1", "Core"],
    openEnrollmentNote: "Massachusetts has additional consumer protections including a continuous open enrollment period for Medicare Supplement plans.",
    stateSpecificRules: [
      "Massachusetts uses its own plan structure: Core, Supplement 1, and Supplement 1A",
      "Continuous open enrollment — you can switch Medigap plans at any time",
      "Guaranteed issue rights are broader than federal law",
      "Plans must cover certain benefits not required federally",
    ],
    overview: "Massachusetts is one of three states (along with Minnesota and Wisconsin) that has its own standardized Medigap plan structure. Instead of the federal lettered plans (A through N), Massachusetts offers Core, Supplement 1, and Supplement 1A plans. Massachusetts also provides significantly stronger consumer protections, including a continuous open enrollment period that allows beneficiaries to switch Medigap plans at any time without medical underwriting.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.3 million" },
      { label: "Plan Structure", value: "State-specific (Core, Supp 1, Supp 1A)" },
      { label: "Open Enrollment", value: "Continuous (year-round)" },
      { label: "Guaranteed Issue", value: "Broader than federal" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/massachusetts-medigap-plans/",
    metaTitle: "Massachusetts Medigap Plans 2026: Medicare Supplement in MA",
    metaDescription: "Compare Medicare Supplement plans in Massachusetts. MA has unique state-specific Medigap rules with continuous open enrollment. Find the best plan for 2026.",
  },
  {
    slug: "wisconsin-medigap-plans",
    name: "Wisconsin",
    abbreviation: "WI",
    isStandardized: false,
    standardizationNote: "Wisconsin has its own standardized Medigap plan structure. Wisconsin offers a Basic plan plus optional riders, rather than the federal lettered plans.",
    medicareEnrollees: "1.1 million",
    avgPlanGPremium: "N/A (state-specific plans)",
    topCarriers: ["WPS Health Insurance", "Medica", "Dean Health Plan"],
    popularPlans: ["Basic Plan", "Basic + Riders"],
    openEnrollmentNote: "Wisconsin has a 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Wisconsin uses a Basic plan structure with optional riders instead of lettered plans",
      "Basic plan covers Medicare Part A coinsurance and Part B coinsurance",
      "Optional riders can add coverage for deductibles, foreign travel, and more",
      "Guaranteed issue rights apply during open enrollment",
    ],
    overview: "Wisconsin is one of three states with its own Medigap standardization. Wisconsin offers a Basic plan that covers core Medicare cost-sharing, plus a menu of optional riders that beneficiaries can add for additional coverage. This modular approach gives Wisconsin residents flexibility to customize their coverage, though it can make comparison shopping more complex than in states using the federal lettered plan structure.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.1 million" },
      { label: "Plan Structure", value: "State-specific (Basic + Riders)" },
      { label: "Open Enrollment", value: "6 months from Part B enrollment" },
      { label: "Guaranteed Issue", value: "During open enrollment" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/wisconsin-medigap-plans/",
    metaTitle: "Wisconsin Medigap Plans 2026: Medicare Supplement in WI",
    metaDescription: "Compare Medicare Supplement plans in Wisconsin. WI has unique state-specific Medigap rules with Basic plan and optional riders. Find the best plan for 2026.",
  },
  {
    slug: "minnesota-medigap-plans",
    name: "Minnesota",
    abbreviation: "MN",
    isStandardized: false,
    standardizationNote: "Minnesota has its own standardized Medigap plan structure. Minnesota offers Basic and Extended Basic plans, rather than the federal lettered plans.",
    medicareEnrollees: "1.1 million",
    avgPlanGPremium: "N/A (state-specific plans)",
    topCarriers: ["Medica", "UCare", "HealthPartners"],
    popularPlans: ["Extended Basic", "Basic"],
    openEnrollmentNote: "Minnesota has a 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Minnesota uses Basic and Extended Basic plans instead of federal lettered plans",
      "Extended Basic covers more cost-sharing than Basic",
      "Additional consumer protections beyond federal requirements",
      "Guaranteed issue rights during open enrollment",
    ],
    overview: "Minnesota is one of three states with its own Medigap standardization. Minnesota offers Basic and Extended Basic plans. The Basic plan covers Medicare Part A hospital coinsurance and Part B coinsurance, while the Extended Basic plan adds coverage for Medicare deductibles and other cost-sharing. Minnesota also provides additional consumer protections beyond federal requirements.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.1 million" },
      { label: "Plan Structure", value: "State-specific (Basic, Extended Basic)" },
      { label: "Open Enrollment", value: "6 months from Part B enrollment" },
      { label: "Guaranteed Issue", value: "During open enrollment" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/minnesota-medigap-plans/",
    metaTitle: "Minnesota Medigap Plans 2026: Medicare Supplement in MN",
    metaDescription: "Compare Medicare Supplement plans in Minnesota. MN has unique state-specific Medigap rules. Find the best Medicare Supplement plan for 2026.",
  },
  {
    slug: "florida-medigap-plans",
    name: "Florida",
    abbreviation: "FL",
    isStandardized: true,
    medicareEnrollees: "4.8 million",
    avgPlanGPremium: "$145–$220/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Humana", "Blue Cross Blue Shield of FL"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Florida follows federal Medigap standardization (Plans A–N)",
      "Florida has a Birthday Rule — you can switch to a plan with equal or lesser benefits during the 30 days surrounding your birthday each year without medical underwriting",
      "Large Medicare population means competitive pricing from many carriers",
      "Community-rated pricing is common in Florida",
    ],
    overview: "Florida has one of the largest Medicare populations in the country, with nearly 4.8 million enrollees. The state follows federal Medigap standardization, so all lettered plans (A through N) are available. Florida also has a Birthday Rule that gives beneficiaries an annual window to switch Medigap plans without medical underwriting. The large Medicare market means strong competition among carriers, often resulting in competitive pricing.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "4.8 million" },
      { label: "Avg Plan G Premium", value: "$145–$220/month" },
      { label: "Birthday Rule", value: "Yes — annual switch window" },
      { label: "Most Popular Plan", value: "Plan G" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/florida-medigap-plans/",
    metaTitle: "Florida Medigap Plans 2026: Best Medicare Supplement Plans in FL",
    metaDescription: "Compare Medicare Supplement plans in Florida. FL has a Birthday Rule for switching plans. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "new-jersey-medigap-plans",
    name: "New Jersey",
    abbreviation: "NJ",
    isStandardized: true,
    medicareEnrollees: "1.6 million",
    avgPlanGPremium: "$180–$280/month",
    topCarriers: ["Horizon Blue Cross Blue Shield of NJ", "Aetna", "Mutual of Omaha"],
    popularPlans: ["G", "N"],
    openEnrollmentNote: "New Jersey has guaranteed issue rights for Medigap plans — insurers cannot deny coverage or charge higher premiums based on health status.",
    stateSpecificRules: [
      "New Jersey requires guaranteed issue for all Medigap plans — no medical underwriting",
      "Community rating required — all enrollees pay the same premium regardless of age or health",
      "Premiums tend to be higher than most states due to guaranteed issue requirements",
      "Continuous open enrollment period",
    ],
    overview: "New Jersey has some of the strongest Medigap consumer protections in the country. The state requires guaranteed issue for all Medigap plans, meaning insurers cannot deny coverage or charge higher premiums based on health status. New Jersey also uses community rating, so all enrollees pay the same premium regardless of age. While this means premiums tend to be higher than in most states, it also means anyone can get coverage at any time.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.6 million" },
      { label: "Avg Plan G Premium", value: "$180–$280/month" },
      { label: "Guaranteed Issue", value: "Year-round (all plans)" },
      { label: "Rating Method", value: "Community rated" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/new-jersey-medigap-plans/",
    metaTitle: "New Jersey Medigap Plans 2026: Medicare Supplement in NJ",
    metaDescription: "Compare Medicare Supplement plans in New Jersey. NJ has guaranteed issue rights and community rating. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "texas-medigap-plans",
    name: "Texas",
    abbreviation: "TX",
    isStandardized: true,
    medicareEnrollees: "4.2 million",
    avgPlanGPremium: "$120–$195/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Accendo", "Humana"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Texas follows federal Medigap standardization (Plans A–N)",
      "Large Medicare market with strong carrier competition",
      "Attained-age rating is most common — premiums increase as you age",
      "No state-specific Birthday Rule",
    ],
    overview: "Texas has one of the largest Medicare populations in the country with over 4.2 million enrollees. The state follows federal Medigap standardization and has a highly competitive market with many carriers offering plans. Plan G is by far the most popular choice in Texas, followed by Plan N and High Deductible Plan G. Premiums in Texas are generally competitive, though they vary significantly by region and carrier.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "4.2 million" },
      { label: "Avg Plan G Premium", value: "$120–$195/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Rating Method", value: "Attained-age (most common)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/texas-medigap-plans/",
    metaTitle: "Texas Medigap Plans 2026: Best Medicare Supplement Plans in TX",
    metaDescription: "Compare Medicare Supplement plans in Texas. Find the best Medigap plan and rates for 2026. TX has a large, competitive Medicare market.",
  },
  {
    slug: "california-medigap-plans",
    name: "California",
    abbreviation: "CA",
    isStandardized: true,
    medicareEnrollees: "6.4 million",
    avgPlanGPremium: "$155–$240/month",
    topCarriers: ["Blue Shield of CA", "Anthem Blue Cross", "Aetna", "Mutual of Omaha"],
    popularPlans: ["G", "N", "F"],
    openEnrollmentNote: "California has a Birthday Rule — you can switch to a plan with equal or lesser benefits during the 60 days surrounding your birthday each year without medical underwriting.",
    stateSpecificRules: [
      "California follows federal Medigap standardization (Plans A–N)",
      "California Birthday Rule — 60-day window each year to switch plans without underwriting",
      "Largest Medicare population in the country",
      "Premiums tend to be higher than national average",
    ],
    overview: "California has the largest Medicare population in the country with over 6.4 million enrollees. The state follows federal Medigap standardization and has a Birthday Rule that gives beneficiaries a 60-day window around their birthday each year to switch Medigap plans without medical underwriting. California's large market means many carriers compete for business, though premiums tend to be higher than the national average due to the state's higher cost of living.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "6.4 million" },
      { label: "Avg Plan G Premium", value: "$155–$240/month" },
      { label: "Birthday Rule", value: "Yes — 60-day window" },
      { label: "Most Popular Plan", value: "Plan G" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/california-medigap-plans/",
    metaTitle: "California Medigap Plans 2026: Best Medicare Supplement Plans in CA",
    metaDescription: "Compare Medicare Supplement plans in California. CA has a Birthday Rule for switching plans. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "connecticut-medigap-plans",
    name: "Connecticut",
    abbreviation: "CT",
    isStandardized: true,
    medicareEnrollees: "700,000",
    avgPlanGPremium: "$175–$260/month",
    topCarriers: ["Aetna", "Mutual of Omaha", "Blue Cross Blue Shield of CT"],
    popularPlans: ["G", "N"],
    openEnrollmentNote: "Connecticut has guaranteed issue rights for Medigap plans — insurers cannot deny coverage based on health status.",
    stateSpecificRules: [
      "Connecticut requires guaranteed issue for all Medigap plans",
      "Community rating required — premiums don't vary by age",
      "Continuous open enrollment period",
      "Premiums tend to be higher due to guaranteed issue requirements",
    ],
    overview: "Connecticut, like New Jersey, requires guaranteed issue for all Medigap plans and uses community rating. This means anyone can get a Medigap plan at any time without medical underwriting, and all enrollees pay the same premium regardless of age. While premiums tend to be higher than in most states, Connecticut residents benefit from strong consumer protections.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "700,000" },
      { label: "Avg Plan G Premium", value: "$175–$260/month" },
      { label: "Guaranteed Issue", value: "Year-round (all plans)" },
      { label: "Rating Method", value: "Community rated" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/connecticut-medigap-plans/",
    metaTitle: "Connecticut Medigap Plans 2026: Medicare Supplement in CT",
    metaDescription: "Compare Medicare Supplement plans in Connecticut. CT has guaranteed issue rights and community rating. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "arizona-medigap-plans",
    name: "Arizona",
    abbreviation: "AZ",
    isStandardized: true,
    medicareEnrollees: "1.4 million",
    avgPlanGPremium: "$115–$185/month",
    topCarriers: ["Mutual of Omaha", "Accendo", "Aetna", "Humana"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Arizona follows federal Medigap standardization (Plans A–N)",
      "Competitive market with many carriers",
      "Generally lower premiums than coastal states",
      "Attained-age rating is most common",
    ],
    overview: "Arizona has a large and growing Medicare population, particularly in the Phoenix and Tucson metro areas. The state follows federal Medigap standardization and has a competitive market with many carriers. Premiums in Arizona tend to be lower than in coastal states, making it a relatively affordable state for Medigap coverage. Plan G is the most popular choice, followed by Plan N and High Deductible Plan G.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.4 million" },
      { label: "Avg Plan G Premium", value: "$115–$185/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Competitive, lower premiums" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/arizona-medigap-plans/",
    metaTitle: "Arizona Medigap Plans 2026: Best Medicare Supplement Plans in AZ",
    metaDescription: "Compare Medicare Supplement plans in Arizona. Find the best Medigap plan and rates for 2026. AZ has competitive pricing and many carrier options.",
  },
  {
    slug: "georgia-medigap-plans",
    name: "Georgia",
    abbreviation: "GA",
    isStandardized: true,
    medicareEnrollees: "1.8 million",
    avgPlanGPremium: "$120–$190/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Bankers Fidelity", "Accendo"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Georgia follows federal Medigap standardization (Plans A–N)",
      "Competitive market with regional carriers like Bankers Fidelity",
      "Generally affordable premiums",
      "Attained-age rating is most common",
    ],
    overview: "Georgia has a large Medicare population and a competitive Medigap market. The state follows federal standardization and has both national and regional carriers competing for business. Bankers Fidelity, a Georgia-based carrier, is particularly competitive in the state. Premiums in Georgia are generally affordable, and Plan G is the most popular choice.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.8 million" },
      { label: "Avg Plan G Premium", value: "$120–$190/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Bankers Fidelity (local)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/georgia-medigap-plans/",
    metaTitle: "Georgia Medigap Plans 2026: Best Medicare Supplement Plans in GA",
    metaDescription: "Compare Medicare Supplement plans in Georgia. Find the best Medigap plan and rates for 2026. GA has competitive pricing and both national and regional carriers.",
  },
  {
    slug: "pennsylvania-medigap-plans",
    name: "Pennsylvania",
    abbreviation: "PA",
    isStandardized: true,
    medicareEnrollees: "2.8 million",
    avgPlanGPremium: "$140–$210/month",
    topCarriers: ["Highmark", "Aetna", "Mutual of Omaha", "Humana"],
    popularPlans: ["G", "N", "F"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Pennsylvania follows federal Medigap standardization (Plans A–N)",
      "Highmark (local BCBS affiliate) is a dominant carrier in PA",
      "Large Medicare population with competitive market",
      "Attained-age and issue-age rating both available",
    ],
    overview: "Pennsylvania has a large Medicare population of nearly 2.8 million enrollees. The state follows federal Medigap standardization and has a competitive market. Highmark, the local Blue Cross Blue Shield affiliate, is a dominant carrier in Pennsylvania. Premiums are moderate, and Plan G is the most popular choice. The state has both urban markets (Philadelphia, Pittsburgh) and rural areas with different pricing dynamics.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "2.8 million" },
      { label: "Avg Plan G Premium", value: "$140–$210/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Highmark (local BCBS)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/pennsylvania-medigap-plans/",
    metaTitle: "Pennsylvania Medigap Plans 2026: Best Medicare Supplement Plans in PA",
    metaDescription: "Compare Medicare Supplement plans in Pennsylvania. Find the best Medigap plan and rates for 2026. PA has a large Medicare market with Highmark and national carriers.",
  },
  {
    slug: "oklahoma-medigap-plans",
    name: "Oklahoma",
    abbreviation: "OK",
    isStandardized: true,
    medicareEnrollees: "750,000",
    avgPlanGPremium: "$110–$175/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Accendo", "GPM Life"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Oklahoma follows federal Medigap standardization (Plans A–N)",
      "Generally lower premiums than national average",
      "Competitive market with national and regional carriers",
    ],
    overview: "Oklahoma has a moderate Medicare population and follows federal Medigap standardization. Premiums in Oklahoma tend to be lower than the national average, making it an affordable state for Medigap coverage. The market is competitive with both national carriers and regional options like GPM Life.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "750,000" },
      { label: "Avg Plan G Premium", value: "$110–$175/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Affordable, competitive" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/oklahoma-medigap-plans/",
    metaTitle: "Oklahoma Medigap Plans 2026: Best Medicare Supplement Plans in OK",
    metaDescription: "Compare Medicare Supplement plans in Oklahoma. Find the best Medigap plan and rates for 2026. OK has affordable premiums and a competitive market.",
  },
  {
    slug: "vermont-medigap-plans",
    name: "Vermont",
    abbreviation: "VT",
    isStandardized: true,
    medicareEnrollees: "160,000",
    avgPlanGPremium: "$160–$240/month",
    topCarriers: ["Blue Cross Blue Shield of VT", "Aetna", "Mutual of Omaha"],
    popularPlans: ["G", "N"],
    openEnrollmentNote: "Vermont has guaranteed issue rights for Medigap plans — insurers cannot deny coverage based on health status.",
    stateSpecificRules: [
      "Vermont requires guaranteed issue for all Medigap plans",
      "Community rating required",
      "Continuous open enrollment period",
      "Smaller market with fewer carrier options",
    ],
    overview: "Vermont, like New Jersey and Connecticut, requires guaranteed issue for all Medigap plans and uses community rating. This provides strong consumer protections but results in higher premiums than most states. Vermont has a smaller Medicare population and fewer carrier options than larger states.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "160,000" },
      { label: "Avg Plan G Premium", value: "$160–$240/month" },
      { label: "Guaranteed Issue", value: "Year-round (all plans)" },
      { label: "Rating Method", value: "Community rated" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/vermont-medigap-plans/",
    metaTitle: "Vermont Medigap Plans 2026: Medicare Supplement in VT",
    metaDescription: "Compare Medicare Supplement plans in Vermont. VT has guaranteed issue rights and community rating. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "new-york-medigap-plans",
    name: "New York",
    abbreviation: "NY",
    isStandardized: true,
    medicareEnrollees: "3.8 million",
    avgPlanGPremium: "$200–$320/month",
    topCarriers: ["Empire Blue Cross Blue Shield", "Aetna", "Mutual of Omaha", "Cigna"],
    popularPlans: ["G", "N"],
    openEnrollmentNote: "New York has guaranteed issue rights for Medigap plans year-round — insurers cannot deny coverage based on health status.",
    stateSpecificRules: [
      "New York requires guaranteed issue for all Medigap plans year-round",
      "Community rating required — premiums don't vary by age",
      "Continuous open enrollment period",
      "Among the highest Medigap premiums in the country",
    ],
    overview: "New York has some of the strongest Medigap consumer protections in the country, with year-round guaranteed issue rights and community rating. Anyone can get a Medigap plan at any time without medical underwriting, and all enrollees pay the same premium regardless of age. The trade-off is that New York has among the highest Medigap premiums in the country. The state has a large Medicare population of 3.8 million enrollees.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "3.8 million" },
      { label: "Avg Plan G Premium", value: "$200–$320/month" },
      { label: "Guaranteed Issue", value: "Year-round (all plans)" },
      { label: "Rating Method", value: "Community rated" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/new-york-medigap-plans/",
    metaTitle: "New York Medigap Plans 2026: Medicare Supplement in NY",
    metaDescription: "Compare Medicare Supplement plans in New York. NY has guaranteed issue rights year-round and community rating. Find the best Medigap plan and rates for 2026.",
  },
  {
    slug: "louisiana-medigap-plans",
    name: "Louisiana",
    abbreviation: "LA",
    isStandardized: true,
    medicareEnrollees: "900,000",
    avgPlanGPremium: "$115–$185/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Humana", "Bankers Fidelity"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Louisiana follows federal Medigap standardization (Plans A–N)",
      "Generally affordable premiums",
      "Competitive market with national and regional carriers",
    ],
    overview: "Louisiana follows federal Medigap standardization and has a competitive market with generally affordable premiums. Plan G is the most popular choice, and the state has a good mix of national and regional carriers.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "900,000" },
      { label: "Avg Plan G Premium", value: "$115–$185/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Affordable, competitive" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/louisiana-medigap-plans/",
    metaTitle: "Louisiana Medigap Plans 2026: Best Medicare Supplement Plans in LA",
    metaDescription: "Compare Medicare Supplement plans in Louisiana. Find the best Medigap plan and rates for 2026. LA has affordable premiums and a competitive market.",
  },
  {
    slug: "kentucky-medigap-plans",
    name: "Kentucky",
    abbreviation: "KY",
    isStandardized: true,
    medicareEnrollees: "1.0 million",
    avgPlanGPremium: "$110–$175/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Humana", "Anthem BCBS"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Kentucky follows federal Medigap standardization (Plans A–N)",
      "Humana is headquartered in Louisville — strong local presence",
      "Generally affordable premiums",
    ],
    overview: "Kentucky follows federal Medigap standardization and has a competitive market. Humana, headquartered in Louisville, has a strong presence in the state. Premiums are generally affordable, and Plan G is the most popular choice.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.0 million" },
      { label: "Avg Plan G Premium", value: "$110–$175/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Humana (HQ in Louisville)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/kentucky-medigap-plans/",
    metaTitle: "Kentucky Medigap Plans 2026: Best Medicare Supplement Plans in KY",
    metaDescription: "Compare Medicare Supplement plans in Kentucky. Find the best Medigap plan and rates for 2026. KY has affordable premiums and Humana's home market.",
  },
  {
    slug: "michigan-medigap-plans",
    name: "Michigan",
    abbreviation: "MI",
    isStandardized: true,
    medicareEnrollees: "2.2 million",
    avgPlanGPremium: "$130–$200/month",
    topCarriers: ["Blue Cross Blue Shield of MI", "Mutual of Omaha", "Aetna", "Humana"],
    popularPlans: ["G", "N", "F"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Michigan follows federal Medigap standardization (Plans A–N)",
      "Blue Cross Blue Shield of Michigan is a dominant local carrier",
      "Large Medicare population with competitive market",
    ],
    overview: "Michigan has a large Medicare population and a competitive Medigap market. Blue Cross Blue Shield of Michigan is a dominant local carrier with strong brand recognition. The state follows federal standardization, and premiums are moderate.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "2.2 million" },
      { label: "Avg Plan G Premium", value: "$130–$200/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "BCBS of Michigan (local)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/michigan-medigap-plans/",
    metaTitle: "Michigan Medigap Plans 2026: Best Medicare Supplement Plans in MI",
    metaDescription: "Compare Medicare Supplement plans in Michigan. Find the best Medigap plan and rates for 2026. MI has a large Medicare market with BCBS and national carriers.",
  },
  {
    slug: "mississippi-medigap-plans",
    name: "Mississippi",
    abbreviation: "MS",
    isStandardized: true,
    medicareEnrollees: "650,000",
    avgPlanGPremium: "$105–$170/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Humana", "Bankers Fidelity"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Mississippi follows federal Medigap standardization (Plans A–N)",
      "Among the most affordable states for Medigap premiums",
      "Competitive market with national and regional carriers",
    ],
    overview: "Mississippi is one of the most affordable states for Medigap coverage, with premiums among the lowest in the country. The state follows federal standardization and has a competitive market with both national and regional carriers.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "650,000" },
      { label: "Avg Plan G Premium", value: "$105–$170/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Very affordable premiums" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/mississippi-medigap-plans/",
    metaTitle: "Mississippi Medigap Plans 2026: Best Medicare Supplement Plans in MS",
    metaDescription: "Compare Medicare Supplement plans in Mississippi. Find the best Medigap plan and rates for 2026. MS has some of the most affordable Medigap premiums in the country.",
  },
  {
    slug: "oregon-medigap-plans",
    name: "Oregon",
    abbreviation: "OR",
    isStandardized: true,
    medicareEnrollees: "900,000",
    avgPlanGPremium: "$140–$215/month",
    topCarriers: ["Regence Blue Cross Blue Shield of OR", "Mutual of Omaha", "Aetna"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Oregon follows federal Medigap standardization (Plans A–N)",
      "Regence BCBS is a dominant local carrier",
      "Moderate premiums",
    ],
    overview: "Oregon follows federal Medigap standardization and has a competitive market. Regence Blue Cross Blue Shield of Oregon is a dominant local carrier. Premiums are moderate, and Plan G is the most popular choice.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "900,000" },
      { label: "Avg Plan G Premium", value: "$140–$215/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Regence BCBS (local)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/oregon-medigap-plans/",
    metaTitle: "Oregon Medigap Plans 2026: Best Medicare Supplement Plans in OR",
    metaDescription: "Compare Medicare Supplement plans in Oregon. Find the best Medigap plan and rates for 2026. OR has a competitive market with Regence BCBS and national carriers.",
  },
  {
    slug: "tennessee-medigap-plans",
    name: "Tennessee",
    abbreviation: "TN",
    isStandardized: true,
    medicareEnrollees: "1.4 million",
    avgPlanGPremium: "$115–$185/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Humana", "Cigna"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Tennessee follows federal Medigap standardization (Plans A–N)",
      "Generally affordable premiums",
      "Competitive market with national carriers",
    ],
    overview: "Tennessee follows federal Medigap standardization and has a competitive market with generally affordable premiums. Plan G is the most popular choice, and the state has strong representation from major national carriers.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.4 million" },
      { label: "Avg Plan G Premium", value: "$115–$185/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Affordable, competitive" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/tennessee-medigap-plans/",
    metaTitle: "Tennessee Medigap Plans 2026: Best Medicare Supplement Plans in TN",
    metaDescription: "Compare Medicare Supplement plans in Tennessee. Find the best Medigap plan and rates for 2026. TN has affordable premiums and a competitive market.",
  },
  {
    slug: "ohio-medigap-plans",
    name: "Ohio",
    abbreviation: "OH",
    isStandardized: true,
    medicareEnrollees: "2.5 million",
    avgPlanGPremium: "$125–$195/month",
    topCarriers: ["Medical Mutual of Ohio", "Mutual of Omaha", "Aetna", "Humana"],
    popularPlans: ["G", "N", "F"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Ohio follows federal Medigap standardization (Plans A–N)",
      "Medical Mutual of Ohio is a strong local carrier",
      "Large Medicare population with competitive market",
    ],
    overview: "Ohio has a large Medicare population and a competitive Medigap market. Medical Mutual of Ohio is a strong local carrier with deep roots in the state. The state follows federal standardization, and premiums are moderate.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "2.5 million" },
      { label: "Avg Plan G Premium", value: "$125–$195/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Medical Mutual of Ohio (local)" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/ohio-medigap-plans/",
    metaTitle: "Ohio Medigap Plans 2026: Best Medicare Supplement Plans in OH",
    metaDescription: "Compare Medicare Supplement plans in Ohio. Find the best Medigap plan and rates for 2026. OH has a large Medicare market with Medical Mutual and national carriers.",
  },
  {
    slug: "virginia-medigap-plans",
    name: "Virginia",
    abbreviation: "VA",
    isStandardized: true,
    medicareEnrollees: "1.5 million",
    avgPlanGPremium: "$130–$200/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Anthem BCBS of VA", "Humana"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "Virginia follows federal Medigap standardization (Plans A–N)",
      "Competitive market with national and regional carriers",
      "Moderate premiums",
    ],
    overview: "Virginia follows federal Medigap standardization and has a competitive market. The state has a mix of national carriers and Anthem Blue Cross Blue Shield of Virginia as a regional option. Premiums are moderate.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "1.5 million" },
      { label: "Avg Plan G Premium", value: "$130–$200/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Notable Carrier", value: "Anthem BCBS of VA" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/virginia-medigap-plans/",
    metaTitle: "Virginia Medigap Plans 2026: Best Medicare Supplement Plans in VA",
    metaDescription: "Compare Medicare Supplement plans in Virginia. Find the best Medigap plan and rates for 2026. VA has a competitive market with Anthem BCBS and national carriers.",
  },
  {
    slug: "new-mexico-medigap-plans",
    name: "New Mexico",
    abbreviation: "NM",
    isStandardized: true,
    medicareEnrollees: "430,000",
    avgPlanGPremium: "$110–$175/month",
    topCarriers: ["Mutual of Omaha", "Aetna", "Accendo", "Oxford Life"],
    popularPlans: ["G", "N", "HD-G"],
    openEnrollmentNote: "Standard 6-month open enrollment period starting when you turn 65 and enroll in Medicare Part B.",
    stateSpecificRules: [
      "New Mexico follows federal Medigap standardization (Plans A–N)",
      "Generally affordable premiums",
      "Smaller market with fewer carrier options than larger states",
    ],
    overview: "New Mexico follows federal Medigap standardization and has generally affordable premiums. The state has a smaller Medicare population than most, which means fewer carrier options, but national carriers like Mutual of Omaha and Aetna are well-represented.",
    keyFacts: [
      { label: "Medicare Enrollees", value: "430,000" },
      { label: "Avg Plan G Premium", value: "$110–$175/month" },
      { label: "Most Popular Plan", value: "Plan G" },
      { label: "Market", value: "Affordable, fewer options" },
    ],
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-state/new-mexico-medigap-plans/",
    metaTitle: "New Mexico Medigap Plans 2026: Medicare Supplement in NM",
    metaDescription: "Compare Medicare Supplement plans in New Mexico. Find the best Medigap plan and rates for 2026. NM has affordable premiums and national carrier options.",
  },
];

export function getStateBySlug(slug: string): StateData | undefined {
  return STATE_DATA.find((s) => s.slug === slug);
}
