/**
 * Medigap by-carrier data
 * Used by MedigapCarrierTemplate.tsx
 */

export interface CarrierPlan {
  letter: string;
  available: boolean;
  note?: string;
}

export interface CarrierData {
  slug: string;
  name: string;
  shortName: string;
  amBestRating: string;
  founded: string;
  hq: string;
  statesAvailable: number | string;
  popularPlans: string[];
  plans: CarrierPlan[];
  overview: string;
  strengths: string[];
  considerations: string[];
  bestFor: string;
  notIdealFor: string;
  pricingTier: "budget" | "mid" | "premium";
  pricingNote: string;
  phone: string;
  website: string;
  canonical: string;
  ogImage: string;
  metaTitle: string;
  metaDescription: string;
  relatedCarriers?: string[];
}

const ALL_PLANS: string[] = ["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"];

function plans(available: string[], notes: Record<string, string> = {}): CarrierPlan[] {
  return ALL_PLANS.map((l) => ({
    letter: l,
    available: available.includes(l),
    note: notes[l],
  }));
}

export const CARRIER_DATA: CarrierData[] = [
  {
    slug: "accendo-medicare-supplement-plans",
    name: "Accendo Insurance Company",
    shortName: "Accendo",
    amBestRating: "A (Excellent)",
    founded: "2017",
    hq: "Cedar Rapids, IA",
    statesAvailable: 33,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"], { "F": "Not available to new Medicare enrollees after Jan 1, 2020" }),
    overview: "Accendo Insurance Company is a subsidiary of CVS Health (Aetna), one of the largest healthcare companies in the United States. Accendo currently offers Medicare Supplement plans in approximately 33 states after exiting 14+ state markets since 2023. They are known for competitive pricing, particularly for Plan G and Plan N. As part of the CVS Health family, Accendo benefits from significant financial backing and operational scale. Their Medigap plans are sold through licensed independent agents and brokers.",
    strengths: [
      "Competitive pricing, especially for Plan G and Plan N",
      "Backed by CVS Health — strong financial stability",
      "Available in 33 states",
      "Household discount available in most states",
      "Strong A (Excellent) AM Best rating"],
    considerations: [
      "Relatively newer company (founded 2017) — less historical rate stability data",
      "Has exited 14+ states since 2023 (including CO, GA, IN, IA, NJ, OH, OR, PA)",
      "Customer service primarily through independent agents"],
    bestFor: "Enrollees looking for competitive Plan G or Plan N pricing in states where Accendo is still active.",
    notIdealFor: "Enrollees who prefer a carrier with a very long track record of rate stability.",
    pricingTier: "budget",
    pricingNote: "Accendo is consistently among the lower-priced carriers for Plan G and Plan N in most states.",
    phone: "(888) 335-8996",
    website: "accendo.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/accendo-medicare-supplement-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Accendo Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Accendo Medicare Supplement plans, rates, and reviews. See which Medigap plans Accendo offers and whether they're right for you in 2026.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "cigna-medigap-plans", "humana-medigap-plans"],
  },
  {
    slug: "medico-medigap-plans",
    name: "Medico Insurance Company (Wellabe)",
    shortName: "Medico",
    amBestRating: "A (Excellent)",
    founded: "1930",
    hq: "Des Moines, IA",
    statesAvailable: 27,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "Medico Insurance Company, a subsidiary of Wellabe, Inc., has been providing insurance products since 1930 and is headquartered in Des Moines, Iowa. Medico offers Medicare Supplement plans in 27 states and is known for stable rates and solid customer service. Wellabe (formerly known as CUNA Mutual's insurance division) provides strong financial backing. Medico's Medigap plans are available through independent agents and are particularly popular in the Midwest and South.",
    strengths: [
      "Long history of rate stability since 1930",
      "Subsidiary of Wellabe — A (Excellent) AM Best rating",
      "Competitive pricing in many Midwestern states",
      "Household discount available",
      "Optional dental rider available in select states"],
    considerations: [
      "Available in only 27 states (reduced from prior years)",
      "Less name recognition than some larger carriers",
      "Wellabe has been exiting some state markets",
      "Pricing may be less competitive in coastal states"],
    bestFor: "Enrollees in Midwestern states looking for a carrier with a long track record and stable rates.",
    notIdealFor: "Enrollees in coastal states where other carriers may offer better pricing.",
    pricingTier: "mid",
    pricingNote: "Medico offers competitive mid-range pricing, particularly strong in the Midwest and South.",
    phone: "(888) 335-8996",
    website: "medicoinsurance.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/medico-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Medico Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Medico Medicare Supplement plans, rates, and reviews. See which Medigap plans Medico offers and whether they're right for you in 2026.",
  relatedCarriers: ["bankers-fidelity-medigap-plans", "gpm-medigap-plans", "oxford-life-medigap-plans"],
  },
  {
    slug: "bankers-fidelity-medigap-plans",
    name: "Bankers Fidelity Life Insurance Company",
    shortName: "Bankers Fidelity",
    amBestRating: "A- (Excellent)",
    founded: "1955",
    hq: "Atlanta, GA",
    statesAvailable: 38,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "K", "L", "N"]),
    overview: "Bankers Fidelity Life Insurance Company has been providing insurance since 1955 and is headquartered in Atlanta, Georgia. They offer Medicare Supplement plans in 38 states and are known for competitive pricing in the Southeast. Bankers Fidelity is a smaller, regional carrier that focuses primarily on senior insurance products, including Medicare Supplement and life insurance.",
    strengths: [
      "Competitive pricing in Southeastern states",
      "Long history since 1955",
      "Focused exclusively on senior insurance products",
      "A- (Excellent) AM Best rating",
      "Household discount available"],
    considerations: [
      "Limited state availability (38 states)",
      "Smaller company with fewer resources than national carriers",
      "Less competitive outside the Southeast"],
    bestFor: "Enrollees in Southeastern states looking for competitive pricing from a regionally focused carrier.",
    notIdealFor: "Enrollees who prioritize the highest financial strength ratings or need coverage in all 50 states.",
    pricingTier: "budget",
    pricingNote: "Bankers Fidelity is often competitively priced in the Southeast, particularly for Plan G.",
    phone: "(888) 335-8996",
    website: "bankersfidelity.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/bankers-fidelity-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Bankers Fidelity Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Bankers Fidelity Medicare Supplement plans, rates, and reviews. See which Medigap plans they offer and whether they're right for you in 2026.",
  relatedCarriers: ["medico-medigap-plans", "gpm-medigap-plans", "national-general"],
  },
  {
    slug: "united-american-medigap-plans",
    name: "United American Insurance Company",
    shortName: "United American",
    amBestRating: "A (Excellent)",
    founded: "1947",
    hq: "McKinney, TX",
    statesAvailable: 50,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "United American Insurance Company has been providing insurance products since 1947 and is a subsidiary of Globe Life Inc. (formerly Torchmark Corporation), one of the largest life and health insurance companies in the United States. United American offers Medicare Supplement plans in all 50 states and is known for its broad availability and competitive pricing. They offer one of the most complete plan lineups of any Medigap carrier.",
    strengths: [
      "Available in all 50 states",
      "Complete plan lineup — all Medigap plan letters offered",
      "Subsidiary of Globe Life Inc. — strong financial backing",
      "A (Excellent) AM Best rating",
      "Long history since 1947"],
    considerations: [
      "Pricing varies significantly by state",
      "Rate increases have been higher than average in some states",
      "Customer service quality varies by agent"],
    bestFor: "Enrollees who want the widest plan selection from a financially strong carrier available in all 50 states.",
    notIdealFor: "Enrollees in states where United American has had above-average rate increases.",
    pricingTier: "mid",
    pricingNote: "United American offers mid-range pricing with significant variation by state. Competitive in some markets, higher in others.",
    phone: "(888) 335-8996",
    website: "unitedamerican.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/united-american-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "United American Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare United American Medicare Supplement plans, rates, and reviews. Available in all 50 states. See which Medigap plans are right for you in 2026.",
  relatedCarriers: ["mutual-of-omaha-medigap-plans", "aetna-medicare-supplement-plans", "humana-medigap-plans"],
  },
  {
    slug: "united-healthcare-medigap-plans",
    name: "UnitedHealthcare Medicare Supplement",
    shortName: "UnitedHealthcare",
    amBestRating: "A+ (Superior)",
    founded: "1977",
    hq: "Minnetonka, MN",
    statesAvailable: 50,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "UnitedHealthcare is the largest health insurer in the United States and one of the most recognized names in Medicare. Their Medicare Supplement plans are underwritten by AARP and marketed through the AARP Medicare Supplement Insurance Program. UnitedHealthcare's Medigap plans are available in all 50 states and are known for their brand recognition, member benefits, and broad availability. AARP membership (available to anyone 50+) is required to enroll.",
    strengths: [
      "Largest health insurer in the U.S. — exceptional financial strength",
      "Available in all 50 states",
      "AARP brand recognition and member benefits",
      "Household discount available",
      "Additional member benefits (fitness, vision discounts)",
      "A+ (Superior) AM Best rating"],
    considerations: [
      "Typically higher premiums than many competitors",
      "AARP membership required ($16/year)",
      "Rate increases have been above average in some states",
      "Not always the best value for budget-conscious enrollees"],
    bestFor: "Enrollees who value brand recognition, broad availability, and AARP member benefits, and who are less price-sensitive.",
    notIdealFor: "Budget-conscious enrollees — UnitedHealthcare typically charges a premium for its brand name.",
    pricingTier: "premium",
    pricingNote: "UnitedHealthcare is typically among the higher-priced carriers. The AARP brand and member benefits command a premium.",
    phone: "(888) 335-8996",
    website: "uhcmedicare.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/united-healthcare-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "UnitedHealthcare Medicare Supplement Plans 2026: AARP Medigap Rates",
    metaDescription: "Compare UnitedHealthcare (AARP) Medicare Supplement plans, rates, and reviews. See all Medigap plan options and 2026 pricing from UnitedHealthcare.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "blue-cross-blue-shield-medigap-plans",
    name: "Blue Cross Blue Shield Medicare Supplement",
    shortName: "Blue Cross Blue Shield",
    amBestRating: "A to A+ (varies by plan)",
    founded: "1929",
    hq: "Various (34 independent companies)",
    statesAvailable: 50,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"], { "C": "Availability varies by state plan" }),
    overview: "Blue Cross Blue Shield (BCBS) is one of the most recognized names in American health insurance. BCBS Medicare Supplement plans are offered through a federation of 34 independent, locally operated companies that collectively provide coverage in all 50 states. Because each BCBS plan is independently operated, plan availability, pricing, and customer service can vary significantly by state. BCBS is known for its strong brand recognition and broad provider networks.",
    strengths: [
      "One of the most recognized names in health insurance",
      "Available in all 50 states through local plans",
      "Strong financial stability across the federation",
      "Long history since 1929",
      "Local customer service in most states"],
    considerations: [
      "Pricing and plan availability vary significantly by state",
      "Not a single national carrier — each state plan operates independently",
      "Often higher-priced than regional competitors",
      "Rate history varies by state plan"],
    bestFor: "Enrollees who value brand recognition and want to work with a locally operated plan that knows their state's market.",
    notIdealFor: "Enrollees who want consistent national pricing or the lowest possible premiums.",
    pricingTier: "premium",
    pricingNote: "BCBS pricing varies significantly by state. In some states they're competitive; in others they're among the most expensive.",
    phone: "(888) 335-8996",
    website: "bcbs.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/blue-cross-blue-shield-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Blue Cross Blue Shield Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Blue Cross Blue Shield Medicare Supplement plans, rates, and reviews. See BCBS Medigap plan options and 2026 pricing in your state.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "united-healthcare-medigap-plans", "cigna-medigap-plans"],
  },
  {
    slug: "cigna-medigap-plans",
    name: "HealthSpring Medicare Supplement (formerly Cigna)",
    shortName: "HealthSpring",
    amBestRating: "A (Excellent)",
    founded: "1982",
    hq: "Chicago, IL",
    statesAvailable: 45,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "F", "G", "HD-F", "HD-G", "N"]),
    overview: "HealthSpring (formerly Cigna Medicare) is the rebranded Medicare division now operated by Health Care Service Corporation (HCSC). In 2026, Cigna's Medicare business fully transitioned to the HealthSpring brand. HealthSpring Medicare Supplement plans are available in 45 states and are known for competitive pricing, particularly for Plan G and Plan N. Existing Cigna Medigap policyholders have been transitioned to Medco Containment Life Insurance Company, while new policies are issued under the HealthSpring brand.",
    strengths: [
      "Backed by HCSC — one of the largest health insurers in the U.S.",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "Up to 25% discount (20% premium + 5% online application)",
      "Strong customer service infrastructure"],
    considerations: [
      "Recent rebrand from Cigna — brand still transitioning",
      "Not available in all states (45 of 50)",
      "Existing Cigna policies transferred to Medco Containment Life",
      "Plan availability varies by state"],
    bestFor: "Enrollees looking for competitive Plan G or Plan N pricing from a financially strong carrier with significant discounts.",
    notIdealFor: "Enrollees in states where HealthSpring is not available or those uncomfortable with a recently rebranded carrier.",
    pricingTier: "mid",
    pricingNote: "HealthSpring offers competitive mid-range pricing for Plan G and Plan N, with up to 25% in available discounts.",
    phone: "(888) 335-8996",
    website: "healthspring.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/cigna-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "HealthSpring (Cigna) Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare HealthSpring (formerly Cigna) Medicare Supplement plans, rates, and reviews. See which Medigap plans are offered and 2026 pricing.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "blue-cross-blue-shield-medigap-plans"],
  },
  {
    slug: "aetna-medicare-supplement-plans",
    name: "Aetna Medicare Supplement",
    shortName: "Aetna",
    amBestRating: "A (Excellent)",
    founded: "1853",
    hq: "Hartford, CT",
    statesAvailable: 44,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "L", "N"]),
    overview: "Aetna is one of the oldest and most established health insurance companies in the United States, founded in 1853. Now a subsidiary of CVS Health, Aetna offers Medicare Supplement plans in approximately 44 states (primarily through its Accendo subsidiary) and is known for its financial strength, brand recognition, and competitive pricing. Aetna's Medigap plans are available through independent agents and are particularly popular for Plan G. Their long history and CVS Health backing make them a reliable choice.",
    strengths: [
      "One of the oldest insurers in the U.S. (founded 1853)",
      "Subsidiary of CVS Health — exceptional financial strength",
      "Available in 44 states (via Aetna and Accendo subsidiaries)",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "7% household discount available"],
    considerations: [
      "Has been reducing state availability in recent years",
      "Medigap sold through Accendo subsidiary in most states",
      "Pricing can vary significantly by state",
      "Some states have seen above-average rate increases"],
    bestFor: "Enrollees who want a financially strong, nationally recognized carrier with competitive Plan G pricing.",
    notIdealFor: "Enrollees in states where Aetna/Accendo has exited or had higher-than-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Aetna offers competitive mid-range pricing in most states, with some variation by region.",
    phone: "(888) 335-8996",
    website: "aetna.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/aetna-medicare-supplement-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Aetna Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Aetna Medicare Supplement plans, rates, and reviews. See which Medigap plans Aetna offers and whether they're right for you in 2026.",
  relatedCarriers: ["cigna-medigap-plans", "humana-medigap-plans", "united-healthcare-medigap-plans"],
  },
  {
    slug: "humana-medigap-plans",
    name: "Humana Medicare Supplement",
    shortName: "Humana",
    amBestRating: "A (Excellent)",
    founded: "1961",
    hq: "Louisville, KY",
    statesAvailable: 47,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "Humana is one of the largest health insurance companies in the United States and is particularly well-known for its Medicare products. Humana offers Medicare Supplement plans in 47 states and is known for competitive pricing, strong customer service, and a broad range of plan options. Humana's Medigap plans come with additional member benefits including SilverSneakers fitness program access in some states.",
    strengths: [
      "One of the largest Medicare insurers in the U.S.",
      "Available in 47 states",
      "Competitive pricing for Plan G and Plan N",
      "SilverSneakers fitness benefit in some states",
      "A (Excellent) AM Best rating",
      "Household discount available"],
    considerations: [
      "Not available in MA, MN, or WI",
      "Pricing varies significantly by state",
      "Rate increases have been above average in some markets"],
    bestFor: "Enrollees who want a large, nationally recognized carrier with competitive pricing and potential wellness benefits.",
    notIdealFor: "Enrollees in states where Humana has had above-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Humana offers competitive mid-range pricing in most states, with strong pricing in the Southeast and Midwest.",
    phone: "(888) 335-8996",
    website: "humana.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/humana-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Humana Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Humana Medicare Supplement plans, rates, and reviews. See which Medigap plans Humana offers and whether they're right for you in 2026.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "cigna-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "mutual-of-omaha-medigap-plans",
    name: "Mutual of Omaha Medicare Supplement",
    shortName: "Mutual of Omaha",
    amBestRating: "A+ (Superior)",
    founded: "1909",
    hq: "Omaha, NE",
    statesAvailable: 47,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "Mutual of Omaha is one of the most respected names in Medicare Supplement insurance, with a history dating back to 1909. Known for exceptional financial strength (A+ Superior AM Best rating), competitive pricing, and outstanding customer service, Mutual of Omaha is consistently ranked among the best Medigap carriers in the country. They are available in 47 states and are particularly well-regarded for their rate stability and claims processing.",
    strengths: [
      "A+ (Superior) AM Best rating — highest tier",
      "Exceptional rate stability and history",
      "Outstanding customer service and claims processing",
      "Competitive pricing for Plan G, Plan N, and HD-G",
      "Long history since 1909",
      "Household discount available"],
    considerations: [
      "Not available in MA, MN, or WI",
      "Premiums may be slightly higher than some budget carriers",
      "Not the absolute lowest price in every state"],
    bestFor: "Enrollees who prioritize financial strength, rate stability, and customer service — and want a carrier they can trust for the long term.",
    notIdealFor: "Enrollees who are solely focused on finding the absolute lowest premium regardless of carrier quality.",
    pricingTier: "mid",
    pricingNote: "Mutual of Omaha offers excellent value — competitive pricing combined with superior financial strength and rate stability.",
    phone: "(888) 335-8996",
    website: "mutualofomaha.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/mutual-of-omaha-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Mutual of Omaha Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Mutual of Omaha Medicare Supplement plans, rates, and reviews. A+ rated Medigap carrier. See 2026 pricing and plan options.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "united-healthcare-medigap-plans"],
  },
  {
    slug: "gpm-medigap-plans",
    name: "GPM Life (Government Personnel Mutual)",
    shortName: "GPM Life",
    amBestRating: "B++ (Good)",
    founded: "1934",
    hq: "San Antonio, TX",
    statesAvailable: 42,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "GPM Life (Government Personnel Mutual Life Insurance Company) has been providing insurance products since 1934 and is headquartered in San Antonio, Texas. GPM Life is a mutual company owned by its policyholders, offering Medicare Supplement plans in 42 states. They are known for competitive pricing and stable rates, particularly in the South and Midwest. GPM Life focuses on senior insurance products including Medicare Supplement, life insurance, and final expense.",
    strengths: [
      "Competitive pricing in Southern and Midwestern states",
      "Stable rate history",
      "Mutual company — owned by policyholders",
      "Long history since 1934",
      "Household discount available"],
    considerations: [
      "B++ (Good) AM Best rating — lower than most competitors",
      "Smaller carrier with less national recognition",
      "Available in 42 states",
      "Less competitive in coastal states"],
    bestFor: "Enrollees in Midwestern and Plains states looking for competitive pricing from a stable regional carrier.",
    notIdealFor: "Enrollees in coastal states or those who prefer a nationally recognized brand.",
    pricingTier: "budget",
    pricingNote: "GPM Life is often among the lower-priced carriers in Midwestern states.",
    phone: "(888) 335-8996",
    website: "gpmlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/gpm-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "GPM Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare GPM Life Medicare Supplement plans, rates, and reviews. See which Medigap plans GPM Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["medico-medigap-plans", "bankers-fidelity-medigap-plans", "oxford-life-medigap-plans"],
  },
  {
    slug: "gerber-life-medigap-plans",
    name: "Gerber Life Insurance Company",
    shortName: "Gerber Life",
    amBestRating: "A+ (Superior)",
    founded: "1967",
    hq: "White Plains, NY",
    statesAvailable: 44,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-G", "K", "N"]),
    overview: "Gerber Life Insurance Company is a subsidiary of Western & Southern Financial Group and is best known for its children's life insurance products. Gerber Life also offers Medicare Supplement plans in select states. Note: Gerber Life's Medicare Supplement availability is limited, and in many markets they connect consumers with partner agents rather than directly underwriting policies. Their A+ (Superior) AM Best rating (upgraded February 2024) reflects the strong financial backing of Western & Southern Financial Group.",
    strengths: [
      "Subsidiary of Western & Southern Financial Group — strong backing",
      "A+ (Superior) AM Best rating (upgraded Feb 2024)",
      "Competitive pricing where available",
      "Straightforward plan options"],
    considerations: [
      "Limited direct Medigap underwriting — may connect to partner agents in many states",
      "Brand primarily associated with children's insurance",
      "Smaller Medigap market presence than major carriers",
      "Availability may be more limited than advertised"],
    bestFor: "Enrollees in states where Gerber Life directly underwrites Medigap policies, looking for strong financial backing.",
    notIdealFor: "Enrollees who want a dedicated Medicare Supplement carrier with broad direct availability.",
    pricingTier: "budget",
    pricingNote: "Gerber Life is competitively priced where available, but direct availability is limited.",
    phone: "(888) 335-8996",
    website: "gerberlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/gerber-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Gerber Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Gerber Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Gerber Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["manhattan-life-medigap-plans", "oxford-life-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "national-general",
    name: "National General Insurance (Discontinued)",
    shortName: "National General",
    amBestRating: "A (Excellent)",
    founded: "1939",
    hq: "New York, NY",
    statesAvailable: "0 (Exited Market)",
    popularPlans: ["G", "N", "HD-G"],
    plans: plans([]),
    overview: "IMPORTANT: National General (Allstate) has exited the Medicare Supplement market as of 2026 and is no longer accepting new enrollees. Existing policyholders will maintain their coverage as long as premiums are paid, but may face higher-than-usual premium increases due to a shrinking risk pool. National General's Medicare Supplement plans were underwritten by American Heritage Life Insurance Company and National Health Insurance Company. If you currently have a National General Medigap policy, you may want to consider switching to another carrier, especially if you qualify for Guaranteed Issue rights due to your carrier exiting the market.",
    strengths: [
      "Existing policyholders retain coverage",
      "Guaranteed Issue rights may apply for switching carriers"],
    considerations: [
      "NO LONGER ACCEPTING NEW ENROLLEES as of 2026",
      "Exiting the Medicare Supplement market entirely",
      "Existing policyholders may face higher premium increases",
      "Customer service and claims support may decline over time"],
    bestFor: "This carrier is no longer accepting new enrollees. Existing policyholders should consider their options.",
    notIdealFor: "Anyone looking for a new Medicare Supplement policy — National General is no longer available.",
    pricingTier: "budget",
    pricingNote: "No longer issuing new policies. Existing policyholders should compare rates with active carriers.",
    phone: "(888) 335-8996",
    website: "nationalgeneral.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/national-general/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "National General Medicare Supplement: Market Exit 2026 — What to Know",
    metaDescription: "National General (Allstate) has exited the Medicare Supplement market in 2026. Learn what this means for existing policyholders and your options.",
  relatedCarriers: ["mutual-of-omaha-medigap-plans", "bankers-fidelity-medigap-plans", "gpm-medigap-plans"],
  },
  {
    slug: "manhattan-life-medigap-plans",
    name: "Manhattan Life Insurance Company",
    shortName: "Manhattan Life",
    amBestRating: "A- (Excellent)",
    founded: "1850",
    hq: "Houston, TX",
    statesAvailable: 40,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "Manhattan Life Insurance Company has one of the longest histories of any insurance company in the United States, founded in 1850. They offer Medicare Supplement plans in 40 states and are known for competitive pricing and stable rates. Manhattan Life is a smaller carrier that focuses on senior insurance products and is particularly competitive in certain regional markets.",
    strengths: [
      "One of the oldest insurance companies in the U.S. (founded 1850)",
      "A- (Excellent) AM Best rating",
      "Competitive pricing in certain regional markets",
      "Stable rate history",
      "Household discount available"],
    considerations: [
      "Available in only 40 states",
      "Smaller carrier with less national recognition",
      "Less competitive in some markets"],
    bestFor: "Enrollees in states where Manhattan Life has strong pricing and rate history.",
    notIdealFor: "Enrollees in states where Manhattan Life is not available or where larger carriers offer better value.",
    pricingTier: "budget",
    pricingNote: "Manhattan Life offers competitive pricing in select regional markets.",
    phone: "(888) 335-8996",
    website: "manhattanlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/manhattan-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Manhattan Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Manhattan Life Medicare Supplement plans, rates, and reviews. See which Medigap plans they offer and whether they're right for you in 2026.",
  relatedCarriers: ["gerber-life-medigap-plans", "oxford-life-medigap-plans", "medico-medigap-plans"],
  },
  {
    slug: "oxford-life-medigap-plans",
    name: "Oxford Life Insurance Company",
    shortName: "Oxford Life",
    amBestRating: "A (Excellent)",
    founded: "1965",
    hq: "Phoenix, AZ",
    statesAvailable: 38,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-G", "K", "N"]),
    overview: "Oxford Life Insurance Company has been providing insurance products since 1965 and is headquartered in Phoenix, Arizona. Oxford Life offers Medicare Supplement plans in 38 states and is known for competitive pricing in the Southwest and Mountain West regions. They are a smaller, regional carrier that focuses on senior insurance products.",
    strengths: [
      "Competitive pricing in Southwestern states",
      "A (Excellent) AM Best rating",
      "Stable rate history",
      "Household discount available"],
    considerations: [
      "Available in only 38 states",
      "Smaller carrier with less national recognition",
      "Less competitive outside the Southwest"],
    bestFor: "Enrollees in Southwestern and Mountain West states looking for competitive pricing from a regional carrier.",
    notIdealFor: "Enrollees outside the Southwest or those who prefer a nationally recognized carrier.",
    pricingTier: "budget",
    pricingNote: "Oxford Life is often competitively priced in Southwestern states.",
    phone: "(888) 335-8996",
    website: "oxfordlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/oxford-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Oxford Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Oxford Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Oxford Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["manhattan-life-medigap-plans", "gerber-life-medigap-plans", "gpm-medigap-plans"],
  }];

export function getCarrierBySlug(slug: string): CarrierData | undefined {
  return CARRIER_DATA.find((c) => c.slug === slug);
}
