/**
 * Medigap by-carrier data
 * Used by MedigapCarrierTemplate.tsx
 */

export interface CarrierPlan {
  letter: string;
  available: boolean;
  note?: string;
}

export interface CarrierData {
  slug: string;
  name: string;
  shortName: string;
  amBestRating: string;
  founded: string;
  hq: string;
  statesAvailable: number | string;
  popularPlans: string[];
  plans: CarrierPlan[];
  overview: string;
  strengths: string[];
  considerations: string[];
  bestFor: string;
  notIdealFor: string;
  pricingTier: "budget" | "mid" | "premium" | "quote";
  pricingNote: string;
  phone: string;
  website: string;
  canonical: string;
  ogImage: string;
  metaTitle: string;
  metaDescription: string;
  relatedCarriers?: string[];
  review?: {
    date: string;
    availability: string;
    ratingNote: string;
    facts: { label: string; text: string; source: string; sourceLabel: string }[];
    faqs: { question: string; answer: string }[];
  };
}

const ALL_PLANS: string[] = ["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"];

function plans(available: string[], notes: Record<string, string> = {}): CarrierPlan[] {
  return ALL_PLANS.map((l) => ({
    letter: l,
    available: available.includes(l),
    note: notes[l],
  }));
}

export const CARRIER_DATA: CarrierData[] = [
  {
    slug: "accendo-medicare-supplement-plans",
    name: "Accendo Insurance Company",
    shortName: "Accendo",
    amBestRating: "A (Excellent)",
    founded: "1955",
    hq: "Salt Lake City, UT",
    statesAvailable: 33,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "D", "F", "G", "K", "L", "M", "N"], { "F": "Not available to new Medicare enrollees after Jan 1, 2020" }),
    overview: "Accendo Insurance Company, founded in 1955 and headquartered in Salt Lake City, Utah, is a subsidiary of CVS Health (Aetna). Accendo currently offers Medicare Supplement plans in approximately 33 states after exiting 14+ state markets since 2023. They are known for competitive pricing, particularly for Plan G and Plan N, and offer a 14% household discount in select states. As part of the CVS Health family, Accendo benefits from significant financial backing and operational scale.",
    strengths: [
      "Competitive pricing, especially for Plan G and Plan N",
      "Backed by CVS Health - strong financial stability",
      "14% household discount in select states",
      "A (Excellent) AM Best rating",
      "Broad plan selection (9 plan letters)"],
    considerations: [
      "Has exited 14+ states since 2023 (including CO, GA, IN, IA, NJ, OH, OR, PA)",
      "Household discount only available in select states (not all 33)",
      "Customer service primarily through independent agents"],
    bestFor: "Enrollees looking for competitive Plan G or Plan N pricing with a strong household discount in states where Accendo is still active.",
    notIdealFor: "Enrollees in states where Accendo has recently exited or who want the broadest state availability.",
    pricingTier: "budget",
    pricingNote: "Accendo is consistently among the lower-priced carriers for Plan G and Plan N in most states.",
    phone: "(888) 335-8996",
    website: "accendo.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/accendo-medicare-supplement-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Accendo Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Accendo Medicare Supplement plans, rates, and reviews. See which Medigap plans Accendo offers and whether they're right for you in 2026.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "cigna-medigap-plans", "humana-medigap-plans"],
  },
  {
    slug: "medico-medigap-plans",
    name: "Medico Insurance Company (Wellabe)",
    shortName: "Medico",
    amBestRating: "A (Excellent)",
    founded: "1930",
    hq: "Des Moines, IA",
    statesAvailable: 28,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "F", "HD-F", "G", "HD-G", "N"]),
    overview: "Medico Insurance Company, a subsidiary of Wellabe, Inc. (formerly American Enterprise Group), has been providing insurance products since 1930 and is headquartered in Des Moines, Iowa. Medico offers Medicare Supplement plans in 28 states and is known for stable rates and solid customer service. In May 2025, AM Best affirmed Wellabe's A (Excellent) Financial Strength Rating with a stable outlook. Medico focuses on a streamlined plan selection - offering Plans A, F, G, HD-F, HD-G, and N - and is particularly popular in the Midwest and South.",
    strengths: [
      "Long history of rate stability since 1930",
      "Subsidiary of Wellabe - A (Excellent) AM Best rating affirmed May 2025",
      "Competitive pricing in many Midwestern states",
      "Household discount available",
      "Optional dental rider available in select states",
      "Streamlined plan selection focused on the most popular options"],
    considerations: [
      "Limited plan selection (6 plans - no Plans B, C, D, K, L, or M)",
      "Available in 28 states (not nationwide)",
      "Less name recognition than some larger carriers",
      "Has exited some state markets (AL, MS, OK, UT, WV in late 2024)"],
    bestFor: "Enrollees in Midwestern states looking for a carrier with a long track record and stable rates.",
    notIdealFor: "Enrollees in coastal states where other carriers may offer better pricing.",
    pricingTier: "mid",
    pricingNote: "Medico offers competitive mid-range pricing, particularly strong in the Midwest and South.",
    phone: "(888) 335-8996",
    website: "medicoinsurance.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/medico-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Medico Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Medico Medicare Supplement plans, rates, and reviews. See which Medigap plans Medico offers and whether they're right for you in 2026.",
  relatedCarriers: ["bankers-fidelity-medigap-plans", "gpm-medigap-plans", "oxford-life-medigap-plans"],
  },
  {
    slug: "bankers-fidelity-medigap-plans",
    name: "Bankers Fidelity Life Insurance Company",
    shortName: "Bankers Fidelity",
    amBestRating: "A-; under review (June 17, 2026)",
    founded: "1955",
    hq: "Atlanta, GA",
    statesAvailable: "Confirm availability",
    popularPlans: ["G", "N"],
    plans: plans(["A", "F", "G", "HD-G", "N"]),
    overview: "Bankers Fidelity markets Medicare Supplement insurance through Bankers Fidelity Life Insurance Company, Bankers Fidelity Assurance Company, and Atlantic Capital Life Assurance Company. Identify the insurer on your quote before comparing its financial rating, complaints, policy form, and premium. This review uses official product disclosures and dated rating evidence, not customer-star scores or a national price ranking.",
    strengths: [
      "Official product disclosures identify the issuing companies and policy-form series",
      "Plan G and Plan N options can be compared where offered",
      "Published product materials provide a starting point for checking policy terms"],
    considerations: [
      "The June 17, 2026 AM Best action placed the group ratings under review with negative implications; check for subsequent actions",
      "New-policy availability and plan options require confirmation",
      "No matched premium study or product-specific complaint score is supplied in this review"],
    bestFor: "Worth comparing when the exact issuer offers your chosen plan and a documented quote fits your budget after reviewing the rating update.",
    notIdealFor: "Do not select it based only on an advertised starting price or an older rating summary. Resolve availability, underwriting, and rating questions first.",
    pricingTier: "quote",
    pricingNote: "Request a written quote with the same plan letter, deductible option, effective date, age, tobacco status, and discount assumptions as competing offers. Ask which discounts apply and how premiums can change; this review does not establish that Bankers Fidelity is cheaper than other insurers.",
    phone: "(888) 335-8996",
    website: "bankersfidelity.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/bankers-fidelity-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Bankers Fidelity Medicare Supplement Review 2026",
    metaDescription: "Review Bankers Fidelity Medigap insurers, dated AM Best rating information, policy availability, and questions to ask before comparing a written premium quote.",
    review: {
      date: "2026-09-18",
      availability: "Confirm current new-policy availability with the insurer. The official product page lists exclusions and says plan availability varies; an insurance license alone does not establish that a particular Medigap plan is sold to you.",
      ratingNote: "The dated action below is not a live rating feed. Financial strength is not a customer-service score, price ranking, or guarantee of future performance.",
      facts: [
        { label: "Legal insurer", text: "Product notes identify three issuers: Bankers Fidelity Life, Bankers Fidelity Assurance, and Atlantic Capital Life Assurance. Match your policy-form series to the company on the application.", source: "https://bankersfidelity.com/productnotes/", sourceLabel: "Official product notes" },
        { label: "Rating action: June 17, 2026", text: "AM Best placed the A- (Excellent) financial-strength ratings of all three group members under review with negative implications. This later action supersedes the April stable-outlook summary; it is not itself a downgrade of the letter rating.", source: "https://news.ambest.com/newscontent.aspx?refnum=275148", sourceLabel: "AM Best rating action" },
        { label: "Policy availability", text: "The product disclosures limit where new Medicare Supplement coverage is offered. Confirm the plan letter, deductible option, issuer, and current application requirements before relying on a quote.", source: "https://bankersfidelity.com/medicare-supplement/", sourceLabel: "Official Medicare Supplement disclosures" }
      ],
      faqs: [
        { question: "Which company issues Bankers Fidelity Medicare Supplement policies?", answer: "The brand's disclosures list Bankers Fidelity Life Insurance Company, Bankers Fidelity Assurance Company, and Atlantic Capital Life Assurance Company. Your application and policy identify the legal issuer. Use that exact name for complaint research and rating checks rather than assuming every record about the brand applies to your policy." },
        { question: "What does the Bankers Fidelity rating review mean?", answer: "AM Best's June 17, 2026 action placed the group's A- financial-strength ratings under review with negative implications. That status signals further rating review, not an automatic downgrade or a claim denial. Check AM Best for newer actions before applying; the dated notice here is not a live rating feed." },
        { question: "Is Bankers Fidelity the cheapest Medigap option?", answer: "This review does not establish a lowest-price winner. Compare written quotes for identical plan letters and deductible options using the same applicant details and effective date. Confirm discounts and the exact insurer, then ask for the applicable rating method and available policy-form rate history." }
      ]
    },
  relatedCarriers: ["medico-medigap-plans", "gpm-medigap-plans", "national-general"],
  },
  {
    slug: "united-american-medigap-plans",
    name: "United American Insurance Company",
    shortName: "United American",
    amBestRating: "A (Excellent), company disclosure 11/2025",
    founded: "1947",
    hq: "McKinney, TX",
    statesAvailable: "Confirm availability",
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "HD-F", "G", "HD-G", "K", "L", "N"]),
    overview: "United American Insurance Company is a Globe Life subsidiary founded in 1947, with a Medicare Supplement business dating to 1966. It is not UnitedHealthcare or the AARP Medicare Supplement program. This review separates documented company facts from questions that require a personal quote, policy-form records, or current complaint research.",
    strengths: [
      "Official materials include standard and high-deductible policy options, where approved",
      "Published policy-form identifiers help you match the quote to the coverage",
      "Documented Medicare Supplement history dating to 1966"],
    considerations: [
      "A high-deductible quote is not directly equivalent to standard Plan G or Plan F",
      "Plan availability must be confirmed for your application",
      "No verified above-average rate-increase finding or customer-service score is supplied here"],
    bestFor: "Worth comparing when you want to evaluate standard and high-deductible options using the exact policy forms and a current personal quote.",
    notIdealFor: "Do not choose a high-deductible policy just for its lower premium if you cannot comfortably budget for its additional cost sharing.",
    pricingTier: "quote",
    pricingNote: "Compare the same plan letter and deductible option across insurers. Request the rating method, discount terms, and available rate history for the quoted policy form. We have not established a national price tier or an above-average rate-increase pattern for United American.",
    phone: "(888) 335-8996",
    website: "unitedamerican.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/united-american-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "United American Medicare Supplement Review 2026",
    metaDescription: "Review United American Medigap coverage, standard and high-deductible options, dated financial-rating evidence, and key questions for comparing personal quotes.",
    review: {
      date: "2026-09-18",
      availability: "United American lists multiple policy forms where approved. Confirm which are open to new applicants; company licensing and a national benefit chart do not establish your specific plan availability.",
      ratingNote: "United American's company page reports A (Excellent) as of November 2025. That is the source's rating date, not a new September 2026 affirmation. Check AM Best for the latest rating before applying.",
      facts: [
        { label: "Company identity", text: "United American is a wholly owned Globe Life subsidiary, established in 1947. Its corporate history records a Medicare Supplement program starting in 1966. Do not confuse it with UnitedHealthcare.", source: "https://www2.unitedamerican.com/about", sourceLabel: "Company history and ratings" },
        { label: "Financial-strength evidence", text: "The company reports an AM Best A (Excellent) financial-strength rating as of November 2025. Financial strength does not measure customer satisfaction or establish the best premium.", source: "https://www2.unitedamerican.com/about", sourceLabel: "Company rating disclosure" },
        { label: "Standard versus high deductible", text: "Official materials list both standard and high-deductible Plan F and G policy forms where approved. Check the deductible option before comparing premiums, and verify Plan F eligibility separately.", source: "https://www2.unitedamerican.com/medicare-supplement-policies", sourceLabel: "Official policy information" }
      ],
      faqs: [
        { question: "Is United American the same as UnitedHealthcare?", answer: "No. United American Insurance Company is a Globe Life subsidiary. UnitedHealthcare is a different insurer associated with AARP-branded Medicare Supplement plans. Check the full legal insurer name on your application so you do not apply another company's reviews, financial ratings, or discount rules to your quote." },
        { question: "Does United American offer high-deductible Plan G?", answer: "Its official materials list a high-deductible Plan G policy form where approved. Confirm current availability and the deductible in your Outline of Coverage. Compare high-deductible quotes separately from standard Plan G because the lower premium comes with additional cost sharing before the policy pays." },
        { question: "Does United American have above-average rate increases?", answer: "We have not verified that claim for your policy and do not use it as a finding in this review. Ask for approved increases tied to the same insurer, policy form, plan, and jurisdiction. Past rate history is useful context but cannot guarantee future premiums." }
      ]
    },
  relatedCarriers: ["mutual-of-omaha-medigap-plans", "aetna-medicare-supplement-plans", "humana-medigap-plans"],
  },
  {
    slug: "united-healthcare-medigap-plans",
    name: "UnitedHealthcare Medicare Supplement",
    shortName: "UnitedHealthcare",
    amBestRating: "A+ (Superior)",
    founded: "1977",
    hq: "Minnetonka, MN",
    statesAvailable: 50,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "G", "K", "L", "N"]),
    overview: "UnitedHealthcare is the largest health insurer in the United States and one of the most recognized names in Medicare. Their Medicare Supplement plans are underwritten by AARP and marketed through the AARP Medicare Supplement Insurance Program. UnitedHealthcare's Medigap plans are available in all 50 states and are known for their brand recognition, member benefits, and broad availability. AARP membership (available to anyone 50+) is required to enroll.",
    strengths: [
      "Largest health insurer in the U.S. - exceptional financial strength",
      "Available in all 50 states",
      "AARP brand recognition and member benefits",
      "Household discount available",
      "Additional member benefits (fitness, vision discounts)",
      "A+ (Superior) AM Best rating"],
    considerations: [
      "Typically higher premiums than many competitors",
      "AARP membership required ($15–$20/year)",
      "Rate increases have been above average in some states",
      "Not always the best value for budget-conscious enrollees"],
    bestFor: "Enrollees who value brand recognition, broad availability, and AARP member benefits, and who are less price-sensitive.",
    notIdealFor: "Budget-conscious enrollees - UnitedHealthcare typically charges a premium for its brand name.",
    pricingTier: "premium",
    pricingNote: "UnitedHealthcare is typically among the higher-priced carriers. The AARP brand and member benefits command a premium.",
    phone: "(888) 335-8996",
    website: "uhcmedicare.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/united-healthcare-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "UnitedHealthcare Medicare Supplement Plans 2026: AARP Medigap Rates",
    metaDescription: "Compare UnitedHealthcare (AARP) Medicare Supplement plans, rates, and reviews. See all Medigap plan options and 2026 pricing from UnitedHealthcare.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "blue-cross-blue-shield-medigap-plans",
    name: "Blue Cross Blue Shield Medicare Supplement",
    shortName: "Blue Cross Blue Shield",
    amBestRating: "A to A+ (varies by plan)",
    founded: "1929",
    hq: "Chicago, IL (BCBSA); 33 independent companies",
    statesAvailable: 50,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"], { "C": "Availability varies by state plan" }),
    overview: "Blue Cross Blue Shield (BCBS) is one of the most recognized names in American health insurance. BCBS Medicare Supplement plans are offered through a federation of 33 independent, locally operated companies that collectively provide coverage in all 50 states plus Washington, D.C. Because each BCBS company is independently operated, plan availability, pricing, and customer service can vary significantly by state. Note: Medigap plans do not use provider networks - any doctor who accepts Medicare will accept your BCBS Medigap plan.",
    strengths: [
      "One of the most recognized names in health insurance",
      "Available in all 50 states through local plans",
      "Strong financial stability across the federation",
      "Long history since 1929",
      "Local customer service in most states"],
    considerations: [
      "Pricing and plan availability vary significantly by state",
      "Not a single national carrier - each state plan operates independently",
      "Often higher-priced than regional competitors",
      "Rate history varies by state plan"],
    bestFor: "Enrollees who value brand recognition and want to work with a locally operated plan that knows their state's market.",
    notIdealFor: "Enrollees who want consistent national pricing or the lowest possible premiums.",
    pricingTier: "premium",
    pricingNote: "BCBS pricing varies significantly by state. In some states they're competitive; in others they're among the most expensive.",
    phone: "(888) 335-8996",
    website: "bcbs.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/blue-cross-blue-shield-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Blue Cross Blue Shield Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Blue Cross Blue Shield Medicare Supplement plans, rates, and reviews. See BCBS Medigap plan options and 2026 pricing in your state.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "united-healthcare-medigap-plans", "cigna-medigap-plans"],
  },
  {
    slug: "cigna-medigap-plans",
    name: "HealthSpring Medicare Supplement (formerly Cigna)",
    shortName: "HealthSpring",
    amBestRating: "A (Excellent)",
    founded: "1982",
    hq: "Chicago, IL",
    statesAvailable: 49,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "F", "G", "HD-F", "HD-G", "N"]),
    overview: "HealthSpring (formerly Cigna Medicare) is the rebranded Medicare division now operated by Health Care Service Corporation (HCSC). In 2026, Cigna's Medicare business fully transitioned to the HealthSpring brand. HealthSpring Medicare Supplement plans are available in 48 states plus Washington, D.C. and are known for competitive pricing, particularly for Plan G and Plan N. They offer up to 25% in discounts (20% premium discount + 5% online application). Existing Cigna Medigap policyholders have been transitioned to Medco Containment Life Insurance Company, while new policies are issued under the HealthSpring brand.",
    strengths: [
      "Backed by HCSC - one of the largest health insurers in the U.S.",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "Up to 25% discount (20% premium + 5% online application)",
      "Strong customer service infrastructure"],
    considerations: [
      "Recent rebrand from Cigna - some agents may not yet be contracted",
      "Existing Cigna policies transferred to Medco Containment Life",
      "Limited plan selection (6 plan letters vs. 10+ from some competitors)",
      "Plan availability varies by state"],
    bestFor: "Enrollees looking for competitive Plan G or Plan N pricing from a financially strong carrier with significant discounts.",
    notIdealFor: "Enrollees in states where HealthSpring is not available or those uncomfortable with a recently rebranded carrier.",
    pricingTier: "mid",
    pricingNote: "HealthSpring offers competitive mid-range pricing for Plan G and Plan N, with up to 25% in available discounts.",
    phone: "(888) 335-8996",
    website: "healthspring.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/cigna-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "HealthSpring (Cigna) Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare HealthSpring (formerly Cigna) Medicare Supplement plans, rates, and reviews. See which Medigap plans are offered and 2026 pricing.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "blue-cross-blue-shield-medigap-plans"],
  },
  {
    slug: "aetna-medicare-supplement-plans",
    name: "Aetna Medicare Supplement",
    shortName: "Aetna",
    amBestRating: "A (Excellent)",
    founded: "1853",
    hq: "Hartford, CT",
    statesAvailable: 44,
    popularPlans: ["G", "N", "D"],
    plans: plans(["A", "B", "C", "D", "F", "G", "K", "L", "M", "N"]),
    overview: "Aetna is one of the oldest and most established health insurance companies in the United States, founded in 1853. Now a subsidiary of CVS Health, Aetna offers Medicare Supplement plans in approximately 44 states (primarily through its Accendo subsidiary) and is known for its financial strength, brand recognition, and competitive pricing. Aetna's Medigap plans are available through independent agents and are particularly popular for Plan G. Their long history and CVS Health backing make them a reliable choice.",
    strengths: [
      "One of the oldest insurers in the U.S. (founded 1853)",
      "Subsidiary of CVS Health - exceptional financial strength",
      "Available in 44 states (via Aetna and Accendo subsidiaries)",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "14% household discount available (through Accendo)"],
    considerations: [
      "Has been reducing state availability in recent years",
      "Medigap sold through Accendo subsidiary in most states",
      "Pricing can vary significantly by state",
      "Some states have seen above-average rate increases"],
    bestFor: "Enrollees who want a financially strong, nationally recognized carrier with competitive Plan G pricing.",
    notIdealFor: "Enrollees in states where Aetna/Accendo has exited or had higher-than-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Aetna offers competitive mid-range pricing in most states, with some variation by region.",
    phone: "(888) 335-8996",
    website: "aetna.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/aetna-medicare-supplement-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Aetna Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Aetna Medicare Supplement plans, rates, and reviews. See which Medigap plans Aetna offers and whether they're right for you in 2026.",
  relatedCarriers: ["cigna-medigap-plans", "humana-medigap-plans", "united-healthcare-medigap-plans"],
  },
  {
    slug: "humana-medigap-plans",
    name: "Humana Medicare Supplement",
    shortName: "Humana",
    amBestRating: "A (Excellent)",
    founded: "1961",
    hq: "Louisville, KY",
    statesAvailable: 47,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "C", "F", "G", "HD-F", "HD-G", "K", "L", "N"]),
    overview: "Humana is one of the largest health insurance companies in the United States and is particularly well-known for its Medicare products. Humana offers Medicare Supplement plans in 47 states through multiple underwriting subsidiaries and is known for competitive pricing, strong customer service, and a broad range of plan options. Humana offers a 6% online enrollment discount in most states.",
    strengths: [
      "One of the largest Medicare insurers in the U.S.",
      "Available in 47 states",
      "Competitive pricing for Plan G and Plan N",
      "6% online enrollment discount (most states)",
      "A (Excellent) AM Best rating",
      "High-deductible Plan G option available"],
    considerations: [
      "Online discount not available in CA, CT, OH, and PA",
      "Pricing varies significantly by state",
      "Rate increases have been above average in some markets"],
    bestFor: "Enrollees who want a large, nationally recognized carrier with competitive pricing and a 6% online enrollment discount.",
    notIdealFor: "Enrollees in states where Humana has had above-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Humana offers competitive mid-range pricing in most states, with strong pricing in the Southeast and Midwest.",
    phone: "(888) 335-8996",
    website: "humana.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/humana-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Humana Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Humana Medicare Supplement plans, rates, and reviews. See which Medigap plans Humana offers and whether they're right for you in 2026.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "cigna-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "mutual-of-omaha-medigap-plans",
    name: "Mutual of Omaha Medicare Supplement",
    shortName: "Mutual of Omaha",
    amBestRating: "A+ (Superior)",
    founded: "1909",
    hq: "Omaha, NE",
    statesAvailable: 47,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "M", "N"]),
    overview: "Mutual of Omaha is one of the most respected names in Medicare Supplement insurance, with a history dating back to 1909. Known for exceptional financial strength (A+ Superior AM Best rating), outstanding customer service, and low complaint rates, Mutual of Omaha is consistently ranked among the best Medigap carriers in the country. They are available in 47 states and offer a generous household discount of up to 12%.",
    strengths: [
      "A+ (Superior) AM Best rating - highest tier",
      "Low complaint rates and outstanding customer service",
      "Up to 12% household discount - among the highest in the industry",
      "High-deductible Plan G option for budget-conscious enrollees",
      "Long history since 1909",
      "Covers ~1.3 million beneficiaries nationwide"],
    considerations: [
      "Not available in MA, MN, or WI",
      "Base premiums are typically 23–31% higher than lowest-cost carriers",
      "Recent rate increases have been above average in some markets"],
    bestFor: "Enrollees who prioritize financial strength, rate stability, and customer service - and want a carrier they can trust for the long term.",
    notIdealFor: "Enrollees who are solely focused on finding the absolute lowest premium regardless of carrier quality.",
    pricingTier: "mid",
    pricingNote: "Mutual of Omaha offers excellent value - competitive pricing combined with superior financial strength and rate stability.",
    phone: "(888) 335-8996",
    website: "mutualofomaha.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/mutual-of-omaha-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Mutual of Omaha Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Mutual of Omaha Medicare Supplement plans, rates, and reviews. A+ rated Medigap carrier. See 2026 pricing and plan options.",
  relatedCarriers: ["aetna-medicare-supplement-plans", "humana-medigap-plans", "united-healthcare-medigap-plans"],
  },
  {
    slug: "gpm-medigap-plans",
    name: "GPM Life (Government Personnel Mutual)",
    shortName: "GPM Life",
    amBestRating: "B++ (Good)",
    founded: "1934",
    hq: "San Antonio, TX",
    statesAvailable: 23,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "C", "F", "G", "N"]),
    overview: "GPM Life (Government Personnel Mutual Life Insurance Company) has been providing insurance products since 1934 and is headquartered in San Antonio, Texas. GPM Life is a mutual company owned by its policyholders. Medicare Supplement plans are sold through its subsidiary GPM Health and Life Insurance Company, available in 23 states primarily in the South and Midwest (including TX, GA, IL, IN, OH, NC, and others). They are known for competitive pricing and stable rates. GPM Life offers 5 Medigap plan letters: A, C, F, G, and N.",
    strengths: [
      "Competitive pricing in Southern and Midwestern states",
      "Stable rate history",
      "Mutual company - owned by policyholders",
      "Long history since 1934",
      "7% household discount (available in select states)"],
    considerations: [
      "B++ (Good) AM Best rating - lower than most competitors",
      "Smaller carrier with less national recognition",
      "Limited to 23 states (primarily South and Midwest)",
      "Only 5 plan letters available (A, C, F, G, N)",
      "Not available in Northeast or West Coast states"],
    bestFor: "Enrollees in Midwestern and Plains states looking for competitive pricing from a stable regional carrier.",
    notIdealFor: "Enrollees in coastal states or those who prefer a nationally recognized brand.",
    pricingTier: "budget",
    pricingNote: "GPM Life is often among the lower-priced carriers in Midwestern states.",
    phone: "(888) 335-8996",
    website: "gpmlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/gpm-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "GPM Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare GPM Life Medicare Supplement plans, rates, and reviews. See which Medigap plans GPM Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["medico-medigap-plans", "bankers-fidelity-medigap-plans", "oxford-life-medigap-plans"],
  },
  {
    slug: "gerber-life-medigap-plans",
    name: "Gerber Life Insurance Company",
    shortName: "Gerber Life",
    amBestRating: "A+ (Superior)",
    founded: "1967",
    hq: "Fremont, MI",
    statesAvailable: 32,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "D", "F", "G", "K", "L", "M", "N"]),
    overview: "Gerber Life Insurance Company, a subsidiary of Western & Southern Financial Group since 2019, directly underwrites Medicare Supplement plans in approximately 32 states. While best known for children's life insurance, Gerber Life offers a competitive Medigap product line with 9 plan letters. Their A+ (Superior) AM Best rating reflects the strong financial backing of Western & Southern Financial Group. Gerber Life offers all standardized plans in most states where they operate, with some state-specific limitations.",
    strengths: [
      "Subsidiary of Western & Southern Financial Group - strong financial backing",
      "A+ (Superior) AM Best rating",
      "Competitive pricing in states where available",
      "9 plan letters available including G, N, and F",
      "All plans offered on guarantee issue basis during open enrollment"],
    considerations: [
      "Available in approximately 32 states (not nationwide)",
      "Brand primarily associated with children's insurance",
      "Smaller Medigap market presence than major carriers like UHC or Mutual of Omaha",
      "No household discount publicly advertised"],
    bestFor: "Enrollees in states where Gerber Life operates who want strong financial backing (A+ rated) at competitive prices.",
    notIdealFor: "Enrollees in states where Gerber Life doesn't operate, or those who want a carrier with a dedicated Medicare-focused brand.",
    pricingTier: "budget",
    pricingNote: "Gerber Life is competitively priced in the states where they operate.",
    phone: "(888) 335-8996",
    website: "gerberlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/gerber-life-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Gerber Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Gerber Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Gerber Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["manhattan-life-medigap-plans", "oxford-life-medigap-plans", "mutual-of-omaha-medigap-plans"],
  },
  {
    slug: "national-general",
    name: "National General Insurance (Discontinued)",
    shortName: "National General",
    amBestRating: "A (Excellent) - American Heritage Life",
    founded: "1939",
    hq: "New York, NY (Allstate HQ: Northbrook, IL)",
    statesAvailable: "0 (Exited Market)",
    popularPlans: ["G", "N", "HD-G"],
    plans: plans([]),
    overview: "IMPORTANT: National General (Allstate) is withdrawing from the Medicare Supplement market and is no longer accepting new enrollees as of 2026. This exit affects approximately 44,000 existing Medigap policyholders nationwide. Plans were underwritten by American Heritage Life Insurance Company (AM Best: A (Excellent), downgraded from A+ in May 2025) and National Health Insurance Company (AM Best: A (Excellent), affirmed August 2025). Existing policyholders will maintain their guaranteed-renewable coverage as long as premiums are paid, but may face higher-than-usual premium increases due to a shrinking risk pool. If you currently have a National General Medigap policy, you likely qualify for Guaranteed Issue rights, allowing you to switch to another carrier without medical underwriting.",
    strengths: [
      "Existing policyholders retain guaranteed-renewable coverage",
      "Guaranteed Issue rights apply - switch carriers without medical underwriting",
      "~44,000 affected policyholders have time to transition"],
    considerations: [
      "NO LONGER ACCEPTING NEW ENROLLEES as of 2026",
      "State-by-state withdrawal timeline varies - check your state",
      "Existing policyholders may face higher premium increases (shrinking risk pool)",
      "Customer service and claims support may decline as exit progresses",
      "American Heritage Life AM Best downgraded from A+ to A (Excellent) in May 2025"],
    bestFor: "This carrier is no longer accepting new enrollees. Existing policyholders should use their Guaranteed Issue rights to switch to an active carrier.",
    notIdealFor: "Anyone looking for a new Medicare Supplement policy - National General is no longer available.",
    pricingTier: "budget",
    pricingNote: "No longer issuing new policies. Existing policyholders should compare rates with active carriers using their Guaranteed Issue rights.",
    phone: "(888) 335-8996",
    website: "nationalgeneral.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/national-general/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "National General Medicare Supplement: Market Exit 2026 - What to Know",
    metaDescription: "National General (Allstate) has exited the Medicare Supplement market in 2026. Learn what this means for existing policyholders and your options.",
  relatedCarriers: ["mutual-of-omaha-medigap-plans", "bankers-fidelity-medigap-plans", "gpm-medigap-plans"],
  },
  {
    slug: "manhattan-life-medigap-plans",
    name: "Manhattan Life Insurance Company (Discontinued)",
    shortName: "Manhattan Life",
    amBestRating: "B++ (Good)",
    founded: "1850",
    hq: "Houston, TX",
    statesAvailable: "0 (No New Sales)",
    popularPlans: ["G", "N", "F"],
    plans: plans([]),
    overview: "IMPORTANT: ManhattanLife Insurance and Annuity Corporation discontinued new Medicare Supplement sales in all states effective April 30, 2025. No new applications are being accepted. Existing policyholders are not affected - all in-force policies continue to be serviced as usual. Manhattan Life was founded in 1850 and is one of the oldest insurance companies in the United States. Their Medigap plans (A, C, F, G, and N) were offered in approximately 40 states. Their AM Best rating is B++ (Good), upgraded from B+ in November 2022. If you are looking for a new Medigap policy, please compare other active carriers.",
    strengths: [
      "Existing policyholders retain coverage - all in-force policies continue",
      "One of the oldest insurance companies in the U.S. (founded 1850)",
      "AM Best B++ (Good) rating - upgraded from B+ in November 2022"],
    considerations: [
      "NO LONGER ACCEPTING NEW APPLICATIONS as of April 30, 2025",
      "Discontinued new sales in all states simultaneously",
      "AM Best B++ (Good) - below A-range carriers",
      "Existing policyholders may face higher premium increases over time"],
    bestFor: "This carrier is no longer accepting new enrollees. Existing policyholders should review their options.",
    notIdealFor: "Anyone looking for a new Medicare Supplement policy - Manhattan Life is no longer available for new enrollment.",
    pricingTier: "budget",
    pricingNote: "No longer issuing new policies as of April 30, 2025. Existing policyholders should compare rates with active carriers.",
    phone: "(888) 335-8996",
    website: "manhattanlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/manhattan-life-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Manhattan Life Medicare Supplement: No Longer Accepting New Enrollees (2025)",
    metaDescription: "ManhattanLife discontinued new Medicare Supplement sales in all states as of April 30, 2025. Learn what this means for existing policyholders and your options.",
  relatedCarriers: ["gerber-life-medigap-plans", "oxford-life-medigap-plans", "medico-medigap-plans"],
  },
  {
    slug: "oxford-life-medigap-plans",
    name: "Oxford Life Insurance Company",
    shortName: "Oxford Life",
    amBestRating: "A (Excellent)",
    founded: "1965",
    hq: "Phoenix, AZ",
    statesAvailable: 23,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "F", "G", "N"]),
    overview: "Oxford Life Insurance Company has been providing insurance products since 1965 and is headquartered in Phoenix, Arizona. Oxford Life is a member of AMERCO, the parent company of U-Haul. Oxford Life offers Medicare Supplement plans in 23 states through two subsidiary companies: North American Insurance Company (NAI) and Christian Fidelity Life Insurance Company (CFLIC). They are a smaller, regional carrier focused on senior insurance products and are known for competitive pricing in the Southwest and Mountain West regions. AM Best affirmed their A (Excellent) rating in September 2025.",
    strengths: [
      "A (Excellent) AM Best rating - affirmed September 2025",
      "Competitive pricing in Southwestern and Mountain West states",
      "Member of AMERCO (U-Haul parent) - financially stable holding company",
      "Plans offered through two subsidiaries for broader state coverage"],
    considerations: [
      "Available in only 23 states (AZ, CA, ID, IL, IA, IN, KS, MD, MI, MO, MT, ND, NE, NV, NC, OH, OK, SC, SD, TN, TX, UT, WY)",
      "Limited plan selection - only 4 plan letters (A, F, G, N)",
      "Smaller carrier with less national recognition",
      "Less competitive outside the Southwest and Midwest"],
    bestFor: "Enrollees in Southwestern and Mountain West states looking for competitive pricing from a regional carrier.",
    notIdealFor: "Enrollees outside the 23 available states, or those wanting HD-G, Plan K, or other plan letters.",
    pricingTier: "budget",
    pricingNote: "Oxford Life is often competitively priced in Southwestern and Mountain West states.",
    phone: "(888) 335-8996",
    website: "oxfordlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplement-plans/medigap-by-carrier/oxford-life-medigap-plans/",
    ogImage: "/images/medicarefaq-cover.jpg",
    metaTitle: "Oxford Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Oxford Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Oxford Life offers and whether they're right for you in 2026.",
  relatedCarriers: ["manhattan-life-medigap-plans", "gerber-life-medigap-plans", "gpm-medigap-plans"],
  }];

export function getCarrierBySlug(slug: string): CarrierData | undefined {
  return CARRIER_DATA.find((c) => c.slug === slug);
}
