/**
 * Medigap by-carrier data
 * Used by MedigapCarrierTemplate.tsx
 */

export interface CarrierPlan {
  letter: string;
  available: boolean;
  note?: string;
}

export interface CarrierData {
  slug: string;
  name: string;
  shortName: string;
  amBestRating: string;
  founded: string;
  hq: string;
  statesAvailable: number | string;
  popularPlans: string[];
  plans: CarrierPlan[];
  overview: string;
  strengths: string[];
  considerations: string[];
  bestFor: string;
  notIdealFor: string;
  pricingTier: "budget" | "mid" | "premium";
  pricingNote: string;
  phone: string;
  website: string;
  canonical: string;
  ogImage: string;
  metaTitle: string;
  metaDescription: string;
}

const ALL_PLANS: string[] = ["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"];

function plans(available: string[], notes: Record<string, string> = {}): CarrierPlan[] {
  return ALL_PLANS.map((l) => ({
    letter: l,
    available: available.includes(l),
    note: notes[l],
  }));
}

export const CARRIER_DATA: CarrierData[] = [
  {
    slug: "accendo-medicare-supplement-plans",
    name: "Accendo Insurance Company",
    shortName: "Accendo",
    amBestRating: "A (Excellent)",
    founded: "2017",
    hq: "Cedar Rapids, IA",
    statesAvailable: 47,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"], { "F": "Not available to new Medicare enrollees after Jan 1, 2020" }),
    overview: "Accendo Insurance Company is a subsidiary of CVS Health, one of the largest healthcare companies in the United States. Accendo offers Medicare Supplement plans in most states and is known for competitive pricing, particularly for Plan G and Plan N. As part of the CVS Health family, Accendo benefits from significant financial backing and operational scale. Their Medigap plans are sold through licensed independent agents and brokers nationwide.",
    strengths: [
      "Competitive pricing, especially for Plan G and Plan N",
      "Backed by CVS Health — strong financial stability",
      "Available in 47 states",
      "Household discount available in most states",
      "Strong A (Excellent) AM Best rating",
    ],
    considerations: [
      "Relatively newer company (founded 2017) — less historical rate stability data",
      "Not available in MA, MN, or WI (which have their own standardization rules)",
      "Customer service primarily through independent agents",
    ],
    bestFor: "Enrollees looking for competitive Plan G or Plan N pricing, especially in states where Accendo has strong rate history.",
    notIdealFor: "Enrollees who prefer a carrier with a very long track record of rate stability.",
    pricingTier: "budget",
    pricingNote: "Accendo is consistently among the lower-priced carriers for Plan G and Plan N in most states.",
    phone: "(888) 335-8996",
    website: "accendo.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/accendo-medicare-supplement-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Accendo Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Accendo Medicare Supplement plans, rates, and reviews. See which Medigap plans Accendo offers and whether they're right for you in 2026.",
  },
  {
    slug: "medico-medigap-plans",
    name: "Medico Insurance Company",
    shortName: "Medico",
    amBestRating: "A- (Excellent)",
    founded: "1930",
    hq: "Omaha, NE",
    statesAvailable: 45,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "Medico Insurance Company has been providing insurance products since 1930 and is headquartered in Omaha, Nebraska. Medico offers Medicare Supplement plans in most states and is known for stable rates and solid customer service. They are a subsidiary of CUNA Mutual Group, providing additional financial stability. Medico's Medigap plans are available through independent agents and are particularly popular in the Midwest.",
    strengths: [
      "Long history of rate stability since 1930",
      "Subsidiary of CUNA Mutual Group — strong financial backing",
      "Competitive pricing in many Midwestern states",
      "Household discount available",
      "A- AM Best rating",
    ],
    considerations: [
      "Not available in all states",
      "Less name recognition than some larger carriers",
      "Pricing may be less competitive in coastal states",
    ],
    bestFor: "Enrollees in Midwestern states looking for a carrier with a long track record and stable rates.",
    notIdealFor: "Enrollees in coastal states where other carriers may offer better pricing.",
    pricingTier: "mid",
    pricingNote: "Medico offers competitive mid-range pricing, particularly strong in the Midwest and South.",
    phone: "(888) 335-8996",
    website: "medicoinsurance.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/medico-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Medico Medicare Supplement Plans 2026: Rates, Reviews & Coverage",
    metaDescription: "Compare Medico Medicare Supplement plans, rates, and reviews. See which Medigap plans Medico offers and whether they're right for you in 2026.",
  },
  {
    slug: "bankers-fidelity-medigap-plans",
    name: "Bankers Fidelity Life Insurance Company",
    shortName: "Bankers Fidelity",
    amBestRating: "B+ (Good)",
    founded: "1955",
    hq: "Atlanta, GA",
    statesAvailable: 38,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "K", "L", "N"]),
    overview: "Bankers Fidelity Life Insurance Company has been providing insurance since 1955 and is headquartered in Atlanta, Georgia. They offer Medicare Supplement plans in 38 states and are known for competitive pricing in the Southeast. Bankers Fidelity is a smaller, regional carrier that focuses primarily on senior insurance products, including Medicare Supplement and life insurance.",
    strengths: [
      "Competitive pricing in Southeastern states",
      "Long history since 1955",
      "Focused exclusively on senior insurance products",
      "Household discount available",
    ],
    considerations: [
      "Lower AM Best rating (B+) compared to larger carriers",
      "Limited state availability (38 states)",
      "Smaller company with fewer resources than national carriers",
    ],
    bestFor: "Enrollees in Southeastern states looking for competitive pricing from a regionally focused carrier.",
    notIdealFor: "Enrollees who prioritize the highest financial strength ratings or need coverage in all 50 states.",
    pricingTier: "budget",
    pricingNote: "Bankers Fidelity is often competitively priced in the Southeast, particularly for Plan G.",
    phone: "(888) 335-8996",
    website: "bankersfidelity.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/bankers-fidelity-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Bankers Fidelity Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Bankers Fidelity Medicare Supplement plans, rates, and reviews. See which Medigap plans they offer and whether they're right for you in 2026.",
  },
  {
    slug: "united-american-medigap-plans",
    name: "United American Insurance Company",
    shortName: "United American",
    amBestRating: "A (Excellent)",
    founded: "1947",
    hq: "McKinney, TX",
    statesAvailable: 50,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "United American Insurance Company has been providing insurance products since 1947 and is a subsidiary of Globe Life Inc. (formerly Torchmark Corporation), one of the largest life and health insurance companies in the United States. United American offers Medicare Supplement plans in all 50 states and is known for its broad availability and competitive pricing. They offer one of the most complete plan lineups of any Medigap carrier.",
    strengths: [
      "Available in all 50 states",
      "Complete plan lineup — all Medigap plan letters offered",
      "Subsidiary of Globe Life Inc. — strong financial backing",
      "A (Excellent) AM Best rating",
      "Long history since 1947",
    ],
    considerations: [
      "Pricing varies significantly by state",
      "Rate increases have been higher than average in some states",
      "Customer service quality varies by agent",
    ],
    bestFor: "Enrollees who want the widest plan selection from a financially strong carrier available in all 50 states.",
    notIdealFor: "Enrollees in states where United American has had above-average rate increases.",
    pricingTier: "mid",
    pricingNote: "United American offers mid-range pricing with significant variation by state. Competitive in some markets, higher in others.",
    phone: "(888) 335-8996",
    website: "unitedamerican.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/united-american-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "United American Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare United American Medicare Supplement plans, rates, and reviews. Available in all 50 states. See which Medigap plans are right for you in 2026.",
  },
  {
    slug: "united-healthcare-medigap-plans",
    name: "UnitedHealthcare Medicare Supplement",
    shortName: "UnitedHealthcare",
    amBestRating: "A (Excellent)",
    founded: "1977",
    hq: "Minnetonka, MN",
    statesAvailable: 50,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "UnitedHealthcare is the largest health insurer in the United States and one of the most recognized names in Medicare. Their Medicare Supplement plans are underwritten by AARP and marketed through the AARP Medicare Supplement Insurance Program. UnitedHealthcare's Medigap plans are available in all 50 states and are known for their brand recognition, member benefits, and broad availability. AARP membership (available to anyone 50+) is required to enroll.",
    strengths: [
      "Largest health insurer in the U.S. — exceptional financial strength",
      "Available in all 50 states",
      "AARP brand recognition and member benefits",
      "Household discount available",
      "Additional member benefits (fitness, vision discounts)",
      "A (Excellent) AM Best rating",
    ],
    considerations: [
      "Typically higher premiums than many competitors",
      "AARP membership required ($16/year)",
      "Rate increases have been above average in some states",
      "Not always the best value for budget-conscious enrollees",
    ],
    bestFor: "Enrollees who value brand recognition, broad availability, and AARP member benefits, and who are less price-sensitive.",
    notIdealFor: "Budget-conscious enrollees — UnitedHealthcare typically charges a premium for its brand name.",
    pricingTier: "premium",
    pricingNote: "UnitedHealthcare is typically among the higher-priced carriers. The AARP brand and member benefits command a premium.",
    phone: "(888) 335-8996",
    website: "uhcmedicare.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/united-healthcare-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "UnitedHealthcare Medicare Supplement Plans 2026: AARP Medigap Rates",
    metaDescription: "Compare UnitedHealthcare (AARP) Medicare Supplement plans, rates, and reviews. See all Medigap plan options and 2026 pricing from UnitedHealthcare.",
  },
  {
    slug: "blue-cross-blue-shield-medigap-plans",
    name: "Blue Cross Blue Shield Medicare Supplement",
    shortName: "Blue Cross Blue Shield",
    amBestRating: "A (Excellent)",
    founded: "1929",
    hq: "Various (local plans)",
    statesAvailable: 50,
    popularPlans: ["G", "N", "F"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"], { "C": "Availability varies by state plan" }),
    overview: "Blue Cross Blue Shield (BCBS) is one of the most recognized names in American health insurance. BCBS Medicare Supplement plans are offered through a federation of 34 independent, locally operated companies that collectively provide coverage in all 50 states. Because each BCBS plan is independently operated, plan availability, pricing, and customer service can vary significantly by state. BCBS is known for its strong brand recognition and broad provider networks.",
    strengths: [
      "One of the most recognized names in health insurance",
      "Available in all 50 states through local plans",
      "Strong financial stability across the federation",
      "Long history since 1929",
      "Local customer service in most states",
    ],
    considerations: [
      "Pricing and plan availability vary significantly by state",
      "Not a single national carrier — each state plan operates independently",
      "Often higher-priced than regional competitors",
      "Rate history varies by state plan",
    ],
    bestFor: "Enrollees who value brand recognition and want to work with a locally operated plan that knows their state's market.",
    notIdealFor: "Enrollees who want consistent national pricing or the lowest possible premiums.",
    pricingTier: "premium",
    pricingNote: "BCBS pricing varies significantly by state. In some states they're competitive; in others they're among the most expensive.",
    phone: "(888) 335-8996",
    website: "bcbs.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/blue-cross-blue-shield-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Blue Cross Blue Shield Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Blue Cross Blue Shield Medicare Supplement plans, rates, and reviews. See BCBS Medigap plan options and 2026 pricing in your state.",
  },
  {
    slug: "cigna-medigap-plans",
    name: "Cigna Medicare Supplement",
    shortName: "Cigna",
    amBestRating: "A (Excellent)",
    founded: "1982",
    hq: "Bloomfield, CT",
    statesAvailable: 45,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "L", "N"]),
    overview: "Cigna is a global health services company and one of the largest health insurers in the United States. Cigna's Medicare Supplement plans are available in 45 states and are known for competitive pricing and strong customer service. Cigna offers a range of Medigap plan letters and is particularly competitive for Plan G and Plan N. Their global presence and financial strength make them a reliable long-term Medigap carrier.",
    strengths: [
      "One of the largest health insurers in the U.S.",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "Strong customer service infrastructure",
      "Household discount available",
    ],
    considerations: [
      "Not available in all states (45 of 50)",
      "Pricing can be higher than regional competitors in some states",
      "Plan availability varies by state",
    ],
    bestFor: "Enrollees looking for a large, financially strong carrier with competitive Plan G or Plan N pricing.",
    notIdealFor: "Enrollees in states where Cigna is not available or where smaller regional carriers offer better pricing.",
    pricingTier: "mid",
    pricingNote: "Cigna offers competitive mid-range pricing for Plan G and Plan N in most states.",
    phone: "(888) 335-8996",
    website: "cigna.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/cigna-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Cigna Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Cigna Medicare Supplement plans, rates, and reviews. See which Medigap plans Cigna offers and whether they're right for you in 2026.",
  },
  {
    slug: "aetna-medicare-supplement-plans",
    name: "Aetna Medicare Supplement",
    shortName: "Aetna",
    amBestRating: "A (Excellent)",
    founded: "1853",
    hq: "Hartford, CT",
    statesAvailable: 47,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "L", "N"]),
    overview: "Aetna is one of the oldest and most established health insurance companies in the United States, founded in 1853. Now a subsidiary of CVS Health, Aetna offers Medicare Supplement plans in 47 states and is known for its financial strength, brand recognition, and competitive pricing. Aetna's Medigap plans are available through independent agents and are particularly popular for Plan G. Their long history and CVS Health backing make them a reliable choice.",
    strengths: [
      "One of the oldest insurers in the U.S. (founded 1853)",
      "Subsidiary of CVS Health — exceptional financial strength",
      "Available in 47 states",
      "Competitive pricing for Plan G and Plan N",
      "A (Excellent) AM Best rating",
      "Household discount available",
    ],
    considerations: [
      "Not available in MA, MN, or WI",
      "Pricing can vary significantly by state",
      "Some states have seen above-average rate increases",
    ],
    bestFor: "Enrollees who want a financially strong, nationally recognized carrier with competitive Plan G pricing.",
    notIdealFor: "Enrollees in MA, MN, or WI, or those in states where Aetna has had higher-than-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Aetna offers competitive mid-range pricing in most states, with some variation by region.",
    phone: "(888) 335-8996",
    website: "aetna.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/aetna-medicare-supplement-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Aetna Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Aetna Medicare Supplement plans, rates, and reviews. See which Medigap plans Aetna offers and whether they're right for you in 2026.",
  },
  {
    slug: "humana-medigap-plans",
    name: "Humana Medicare Supplement",
    shortName: "Humana",
    amBestRating: "A- (Excellent)",
    founded: "1961",
    hq: "Louisville, KY",
    statesAvailable: 47,
    popularPlans: ["G", "N", "K"],
    plans: plans(["A", "B", "C", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "Humana is one of the largest health insurance companies in the United States and is particularly well-known for its Medicare products. Humana offers Medicare Supplement plans in 47 states and is known for competitive pricing, strong customer service, and a broad range of plan options. Humana's Medigap plans come with additional member benefits including SilverSneakers fitness program access in some states.",
    strengths: [
      "One of the largest Medicare insurers in the U.S.",
      "Available in 47 states",
      "Competitive pricing for Plan G and Plan N",
      "SilverSneakers fitness benefit in some states",
      "A- (Excellent) AM Best rating",
      "Household discount available",
    ],
    considerations: [
      "Not available in MA, MN, or WI",
      "Pricing varies significantly by state",
      "Rate increases have been above average in some markets",
    ],
    bestFor: "Enrollees who want a large, nationally recognized carrier with competitive pricing and potential wellness benefits.",
    notIdealFor: "Enrollees in states where Humana has had above-average rate increases.",
    pricingTier: "mid",
    pricingNote: "Humana offers competitive mid-range pricing in most states, with strong pricing in the Southeast and Midwest.",
    phone: "(888) 335-8996",
    website: "humana.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/humana-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Humana Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Humana Medicare Supplement plans, rates, and reviews. See which Medigap plans Humana offers and whether they're right for you in 2026.",
  },
  {
    slug: "mutual-of-omaha-medigap-plans",
    name: "Mutual of Omaha Medicare Supplement",
    shortName: "Mutual of Omaha",
    amBestRating: "A+ (Superior)",
    founded: "1909",
    hq: "Omaha, NE",
    statesAvailable: 47,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "L", "M", "N"]),
    overview: "Mutual of Omaha is one of the most respected names in Medicare Supplement insurance, with a history dating back to 1909. Known for exceptional financial strength (A+ Superior AM Best rating), competitive pricing, and outstanding customer service, Mutual of Omaha is consistently ranked among the best Medigap carriers in the country. They are available in 47 states and are particularly well-regarded for their rate stability and claims processing.",
    strengths: [
      "A+ (Superior) AM Best rating — highest tier",
      "Exceptional rate stability and history",
      "Outstanding customer service and claims processing",
      "Competitive pricing for Plan G, Plan N, and HD-G",
      "Long history since 1909",
      "Household discount available",
    ],
    considerations: [
      "Not available in MA, MN, or WI",
      "Premiums may be slightly higher than some budget carriers",
      "Not the absolute lowest price in every state",
    ],
    bestFor: "Enrollees who prioritize financial strength, rate stability, and customer service — and want a carrier they can trust for the long term.",
    notIdealFor: "Enrollees who are solely focused on finding the absolute lowest premium regardless of carrier quality.",
    pricingTier: "mid",
    pricingNote: "Mutual of Omaha offers excellent value — competitive pricing combined with superior financial strength and rate stability.",
    phone: "(888) 335-8996",
    website: "mutualofomaha.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/mutual-of-omaha-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Mutual of Omaha Medicare Supplement Plans 2026: Rates & Reviews",
    metaDescription: "Compare Mutual of Omaha Medicare Supplement plans, rates, and reviews. A+ rated Medigap carrier. See 2026 pricing and plan options.",
  },
  {
    slug: "gpm-medigap-plans",
    name: "GPM Life (Great Plains Energy)",
    shortName: "GPM Life",
    amBestRating: "A- (Excellent)",
    founded: "1949",
    hq: "Omaha, NE",
    statesAvailable: 42,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "GPM Life (Great Plains Energy) has been providing insurance products since 1949 and is headquartered in Omaha, Nebraska. GPM Life offers Medicare Supplement plans in 42 states and is known for competitive pricing and stable rates. They are a smaller, regional carrier that focuses on senior insurance products and is particularly competitive in the Midwest and Plains states.",
    strengths: [
      "Competitive pricing in Midwestern states",
      "Stable rate history",
      "A- (Excellent) AM Best rating",
      "Long history since 1949",
      "Household discount available",
    ],
    considerations: [
      "Smaller carrier with less national recognition",
      "Available in 42 states",
      "Less competitive in coastal states",
    ],
    bestFor: "Enrollees in Midwestern and Plains states looking for competitive pricing from a stable regional carrier.",
    notIdealFor: "Enrollees in coastal states or those who prefer a nationally recognized brand.",
    pricingTier: "budget",
    pricingNote: "GPM Life is often among the lower-priced carriers in Midwestern states.",
    phone: "(888) 335-8996",
    website: "gpmlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/gpm-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "GPM Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare GPM Life Medicare Supplement plans, rates, and reviews. See which Medigap plans GPM Life offers and whether they're right for you in 2026.",
  },
  {
    slug: "gerber-life-medigap-plans",
    name: "Gerber Life Insurance Company",
    shortName: "Gerber Life",
    amBestRating: "A (Excellent)",
    founded: "1967",
    hq: "White Plains, NY",
    statesAvailable: 44,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-G", "K", "N"]),
    overview: "Gerber Life Insurance Company is a subsidiary of Western & Southern Financial Group and is best known for its children's life insurance products. However, Gerber Life also offers Medicare Supplement plans in 44 states and has been growing its Medigap business. They are known for competitive pricing and straightforward plan options. Despite the brand's association with children's products, Gerber Life's Medicare Supplement division is a legitimate and financially strong option.",
    strengths: [
      "Subsidiary of Western & Southern Financial Group — strong backing",
      "A (Excellent) AM Best rating",
      "Competitive pricing in many states",
      "Available in 44 states",
      "Straightforward plan options",
    ],
    considerations: [
      "Brand primarily associated with children's insurance — less Medicare-specific recognition",
      "Not available in all states",
      "Smaller Medigap market presence than major carriers",
    ],
    bestFor: "Enrollees looking for competitive pricing from a financially strong carrier with a straightforward plan lineup.",
    notIdealFor: "Enrollees who prefer a carrier with a long, dedicated Medicare Supplement history.",
    pricingTier: "budget",
    pricingNote: "Gerber Life is often competitively priced, particularly for Plan G in many states.",
    phone: "(888) 335-8996",
    website: "gerberlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/gerber-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Gerber Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Gerber Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Gerber Life offers and whether they're right for you in 2026.",
  },
  {
    slug: "national-general",
    name: "National General Insurance",
    shortName: "National General",
    amBestRating: "A (Excellent)",
    founded: "1939",
    hq: "New York, NY",
    statesAvailable: 43,
    popularPlans: ["G", "N", "HD-G"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "National General Insurance is a subsidiary of Allstate Corporation and has been providing insurance products since 1939. National General offers Medicare Supplement plans in 43 states and is known for competitive pricing and the backing of one of the largest insurance companies in the United States. Their Medigap plans are sold through independent agents and are particularly competitive for Plan G and HD-G.",
    strengths: [
      "Subsidiary of Allstate — exceptional financial backing",
      "A (Excellent) AM Best rating",
      "Competitive pricing for Plan G and HD-G",
      "Available in 43 states",
      "Long history since 1939",
    ],
    considerations: [
      "Not available in all states",
      "Less Medicare-specific brand recognition than dedicated Medicare carriers",
      "Pricing varies by state",
    ],
    bestFor: "Enrollees looking for competitive pricing backed by the financial strength of Allstate.",
    notIdealFor: "Enrollees in states where National General is not available or where other carriers offer better pricing.",
    pricingTier: "budget",
    pricingNote: "National General is often competitively priced, particularly for Plan G and HD-G.",
    phone: "(888) 335-8996",
    website: "nationalgeneral.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/national-general/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "National General Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare National General Medicare Supplement plans, rates, and reviews. See which Medigap plans they offer and whether they're right for you in 2026.",
  },
  {
    slug: "manhattan-life-medigap-plans",
    name: "Manhattan Life Insurance Company",
    shortName: "Manhattan Life",
    amBestRating: "A- (Excellent)",
    founded: "1850",
    hq: "Houston, TX",
    statesAvailable: 40,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-F", "HD-G", "K", "N"]),
    overview: "Manhattan Life Insurance Company has one of the longest histories of any insurance company in the United States, founded in 1850. They offer Medicare Supplement plans in 40 states and are known for competitive pricing and stable rates. Manhattan Life is a smaller carrier that focuses on senior insurance products and is particularly competitive in certain regional markets.",
    strengths: [
      "One of the oldest insurance companies in the U.S. (founded 1850)",
      "A- (Excellent) AM Best rating",
      "Competitive pricing in certain regional markets",
      "Stable rate history",
      "Household discount available",
    ],
    considerations: [
      "Available in only 40 states",
      "Smaller carrier with less national recognition",
      "Less competitive in some markets",
    ],
    bestFor: "Enrollees in states where Manhattan Life has strong pricing and rate history.",
    notIdealFor: "Enrollees in states where Manhattan Life is not available or where larger carriers offer better value.",
    pricingTier: "budget",
    pricingNote: "Manhattan Life offers competitive pricing in select regional markets.",
    phone: "(888) 335-8996",
    website: "manhattanlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/manhattan-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Manhattan Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Manhattan Life Medicare Supplement plans, rates, and reviews. See which Medigap plans they offer and whether they're right for you in 2026.",
  },
  {
    slug: "oxford-life-medigap-plans",
    name: "Oxford Life Insurance Company",
    shortName: "Oxford Life",
    amBestRating: "A- (Excellent)",
    founded: "1965",
    hq: "Phoenix, AZ",
    statesAvailable: 38,
    popularPlans: ["G", "N"],
    plans: plans(["A", "B", "D", "F", "G", "HD-G", "K", "N"]),
    overview: "Oxford Life Insurance Company has been providing insurance products since 1965 and is headquartered in Phoenix, Arizona. Oxford Life offers Medicare Supplement plans in 38 states and is known for competitive pricing in the Southwest and Mountain West regions. They are a smaller, regional carrier that focuses on senior insurance products.",
    strengths: [
      "Competitive pricing in Southwestern states",
      "A- (Excellent) AM Best rating",
      "Stable rate history",
      "Household discount available",
    ],
    considerations: [
      "Available in only 38 states",
      "Smaller carrier with less national recognition",
      "Less competitive outside the Southwest",
    ],
    bestFor: "Enrollees in Southwestern and Mountain West states looking for competitive pricing from a regional carrier.",
    notIdealFor: "Enrollees outside the Southwest or those who prefer a nationally recognized carrier.",
    pricingTier: "budget",
    pricingNote: "Oxford Life is often competitively priced in Southwestern states.",
    phone: "(888) 335-8996",
    website: "oxfordlife.com",
    canonical: "https://www.medicarefaq.com/medicare-supplements/medigap-by-carrier/oxford-life-medigap-plans/",
    ogImage: "https://www.medicarefaq.com/wp-content/uploads/Medicare-Supplement-8.jpg",
    metaTitle: "Oxford Life Medicare Supplement Plans 2026: Medigap Rates & Reviews",
    metaDescription: "Compare Oxford Life Medicare Supplement plans, rates, and reviews. See which Medigap plans Oxford Life offers and whether they're right for you in 2026.",
  },
];

export function getCarrierBySlug(slug: string): CarrierData | undefined {
  return CARRIER_DATA.find((c) => c.slug === slug);
}
