import { NextRequest, NextResponse } from "next/server";

// Pipeline state is stored in localStorage on the client side
// This route handles server-side operations: producing articles from approved briefs

export interface PipelineItem {
  id: string; // S3 dedup ID e.g. incoming/file.json#article-0
  status: "ingested" | "briefed" | "approved" | "rejected" | "producing" | "done" | "failed";
  // Source data from S3
  sourceTitle: string;
  sourceUrl: string;
  sourceCategory: string;
  sourceSnippet: string;
  sourceSeo: {
    suggestedTitle: string;
    metaDescription: string;
    primaryKeyword: string;
    semanticKeywords: string[];
    contentAngle: string;
  };
  topic: string;
  importanceScore: number;
  ingestedAt: string;
  // Brief data (generated by AI)
  brief?: {
    title: string;
    keyword: string;
    secondaryKeywords: string[];
    wordCount: number;
    linkCount: number;
    description: string;
    category: string;
  };
  briefGeneratedAt?: string;
  // Production data
  approvedAt?: string;
  rejectedAt?: string;
  producedAt?: string;
  draftSlug?: string;
  error?: string;
}

// POST: Produce an article from an approved brief
export async function POST(req: NextRequest) {
  try {
    const { item } = await req.json();

    if (!item || !item.brief) {
      return NextResponse.json(
        { error: "Approved pipeline item with brief is required" },
        { status: 400 }
      );
    }

    const brief = item.brief;
    const host = req.headers.get("host") || "localhost:3000";
    const protocol = host.includes("localhost") ? "http" : "https";
    const baseUrl = `${protocol}://${host}`;

    // Step 1: Generate outline from the brief keyword
    const outlineResp = await fetch(`${baseUrl}/api/cms/generate-outline`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        keyword: brief.keyword,
        secondaryKeywords: brief.secondaryKeywords,
        wordCount: brief.wordCount,
        angle: brief.description,
        category: brief.category,
      }),
    });

    if (!outlineResp.ok) {
      const err = await outlineResp.text();
      return NextResponse.json(
        { error: `Outline generation failed: ${err}` },
        { status: 500 }
      );
    }

    const outlineData = await outlineResp.json();
    const outline = outlineData.outline;

    // Step 2: Generate article from outline
    const articleResp = await fetch(
      `${baseUrl}/api/cms/generate-from-outline`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          keyword: brief.keyword,
          secondaryKeywords: brief.secondaryKeywords,
          outline: outline,
          title: brief.title,
          category: brief.category,
          wordCount: brief.wordCount,
        }),
      }
    );

    if (!articleResp.ok) {
      const err = await articleResp.text();
      return NextResponse.json(
        { error: `Article generation failed: ${err}` },
        { status: 500 }
      );
    }

    const articleData = await articleResp.json();

    // Step 3: Generate featured image
    let imageData: any = null;
    try {
      const imageResp = await fetch(`${baseUrl}/api/cms/generate-image`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: brief.title,
          category: brief.category,
          excerpt: articleData.meta?.excerpt || brief.description,
        }),
      });
      if (imageResp.ok) {
        imageData = await imageResp.json();
      }
    } catch {
      // Image generation is non-blocking
    }

    // Step 4: Save as draft
    const slug = brief.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60);

    const draftResp = await fetch(`${baseUrl}/api/cms/drafts`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        id: `pipeline-${slug}`,
        title: articleData.meta?.seoTitle || brief.title,
        slug,
        category: brief.category,
        sections: articleData.sections,
        seoTitle: articleData.meta?.seoTitle || brief.title,
        seoDescription:
          articleData.meta?.seoDescription || brief.description,
        excerpt: articleData.meta?.excerpt || "",
        keyTakeaways: articleData.meta?.keyTakeaways || [],
        pendingImageBase64: imageData?.base64 || null,
        pendingImageFileName: imageData?.fileName || null,
        relatedSlugs: [],
        sourceUrl: item.sourceUrl,
        pipelineId: item.id,
      }),
    });

    if (!draftResp.ok) {
      const err = await draftResp.text();
      return NextResponse.json(
        { error: `Draft save failed: ${err}` },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      slug,
      draftId: `pipeline-${slug}`,
      quality: articleData.quality || null,
    });
  } catch (error: any) {
    console.error("Pipeline produce error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to produce article" },
      { status: 500 }
    );
  }
}
